#ifndef STATOR_H
#define STATOR_H

/* THIS FILE WAS GENERATED BY cbindgen — DO NOT EDIT MANUALLY.
 * Re-run `cargo build -p stator_ffi` to regenerate.
 */

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * An opaque handle to a CDP WebSocket server.
 *
 * Created with [`stator_cdp_server_create`] and freed with
 * [`stator_cdp_server_destroy`].
 */
typedef struct StatorCdpServer StatorCdpServer;

/**
 * An opaque context handle.
 *
 * A context represents an execution environment associated with an
 * [`StatorIsolate`].  The caller must pass the returned pointer to
 * [`stator_context_destroy`] when the context is no longer needed.
 */
typedef struct StatorContext StatorContext;

/**
 * An opaque handle to an interactive debugging session.
 *
 * A debug session owns both the compiled [`InterpreterFrame`] and an attached
 * [`Debugger`], allowing the host to:
 *
 * 1. Set breakpoints before execution starts.
 * 2. Start execution with [`stator_debug_session_run`] — the call returns
 *    `true` when a breakpoint is hit, leaving the session in a paused state.
 * 3. Inspect global variables with [`stator_debug_session_get_global_string`].
 * 4. Resume with [`stator_debug_session_resume`].
 * 5. Repeat until `run` / `resume` return `false` (execution completed).
 * 6. Retrieve the final result with [`stator_debug_session_result`].
 *
 * Created with [`stator_debug_session_create`] and freed with
 * [`stator_debug_session_destroy`].
 */
typedef struct StatorDebugSession StatorDebugSession;

/**
 * An opaque escapable handle scope.
 *
 * Works like [`StatorHandleScope`] but allows a single value to be
 * *escaped* — promoted into the enclosing scope (or left as an embedder-owned
 * handle if there is no enclosing scope) — via
 * [`stator_escapable_handle_scope_escape`].
 *
 * Created by [`stator_escapable_handle_scope_new`] and closed (and its
 * remaining values destroyed) by [`stator_escapable_handle_scope_close`].
 */
typedef struct StatorEscapableHandleScope StatorEscapableHandleScope;

/**
 * Call-site information passed to a function-template callback.
 *
 * The lifetime of a `StatorFunctionCallbackInfo` value is limited to the
 * duration of the native callback invocation; the embedder must not store the
 * pointer beyond that.
 */
typedef struct StatorFunctionCallbackInfo StatorFunctionCallbackInfo;

/**
 * An opaque function template handle.
 *
 * A function template associates a C callback with an isolate so that
 * [`stator_function_template_get_function`] can produce a [`StatorValue`]
 * representing the function, which can then be installed into a context's
 * global environment via [`stator_context_global_set`].
 */
typedef struct StatorFunctionTemplate StatorFunctionTemplate;

/**
 * An opaque handle scope that manages the lifetime of [`StatorValue`] handles
 * created while the scope is open.
 *
 * When a handle scope is open on an isolate, any value created via
 * [`stator_value_new_number`] or [`stator_value_new_string`] is automatically
 * registered with the innermost open scope.  Calling
 * [`stator_handle_scope_close`] destroys all registered values and restores
 * the previous scope.
 *
 * Handle scopes nest: opening a second scope while one is already open is
 * valid; closing it restores the outer scope.
 *
 * # Ownership
 * Values registered with a scope are **owned by the scope**.  The embedder
 * must **not** call [`stator_value_destroy`] on those values; doing so would
 * result in a double-free.
 */
typedef struct StatorHandleScope StatorHandleScope;

/**
 * An opaque isolate handle.
 *
 * An isolate is an independent instance of the Stator engine with its own
 * heap and root set.  Isolates are not thread-safe by default; access from
 * multiple threads requires external synchronisation.
 */
typedef struct StatorIsolate StatorIsolate;

/**
 * An opaque handle to a JavaScript object.
 *
 * Created by [`stator_object_new`] and destroyed by [`stator_object_destroy`].
 * Named properties can be set and retrieved via [`stator_object_set`] and
 * [`stator_object_get`].
 */
typedef struct StatorObject StatorObject;

/**
 * An opaque handle to an embedder-provided platform implementation.
 *
 * Created by [`stator_platform_new`] and destroyed by
 * [`stator_platform_destroy`].
 */
typedef struct StatorPlatform StatorPlatform;

/**
 * An opaque snapshot of the own property names of a JavaScript object.
 *
 * Created by [`stator_object_get_property_names`] and freed by
 * [`stator_property_names_destroy`].  The individual name strings are owned
 * by this snapshot and remain valid until it is destroyed.
 */
typedef struct StatorPropertyNames StatorPropertyNames;

/**
 * The outcome of a `stator_script_compile` call.
 *
 * Created by [`stator_script_compile`] and released by [`stator_script_free`].
 */
typedef struct StatorScript StatorScript;

/**
 * An opaque handle to a JavaScript value (number or string).
 *
 * Created by [`stator_value_new_number`] or [`stator_value_new_string`] and
 * destroyed by [`stator_value_destroy`].  The live-object counter on the
 * parent isolate is incremented on creation and decremented on destruction.
 */
typedef struct StatorValue StatorValue;

/**
 * An opaque handle wrapping a live WebAssembly module instance.
 *
 * Created by [`stator_wasm_instantiate`] and freed by
 * [`stator_wasm_instance_destroy`].
 */
typedef struct StatorWasmInstance StatorWasmInstance;

/**
 * An opaque handle wrapping a compiled WebAssembly module.
 *
 * Created by [`stator_wasm_compile`] and freed by
 * [`stator_wasm_module_destroy`].
 */
typedef struct StatorWasmModule StatorWasmModule;

/**
 * Compilation tier statistics for an isolate.
 *
 * Filled in by `stator_isolate_get_stats`.  All counts are thread-local
 * totals accumulated since the process started (or since the last
 * interpreter reset on this thread).
 *
 * On platforms where the baseline JIT is not available (non-x86-64 or
 * non-Unix), all fields will always be zero.
 */
typedef struct StatorCompilationStats {
  /**
   * Number of JavaScript functions that have been compiled to baseline JIT.
   */
  uint32_t jit_functions_compiled;
  /**
   * Total bytes of machine code produced by the baseline JIT compiler.
   */
  size_t jit_code_bytes;
} StatorCompilationStats;

/**
 * C-callable native-function signature.
 *
 * The callback receives the active context, an array of `argc` argument
 * pointers (owned by the Rust side; **do not free them**), and the count.
 * It must return either a new [`StatorValue`] (caller must free it) or a
 * null pointer (treated as `undefined`).
 */
typedef struct StatorValue *(*StatorNativeCallback)(struct StatorContext *ctx,
                                                    const struct StatorValue *const *args,
                                                    int32_t argc);

/**
 * C-callable function-template callback signature.
 *
 * The callback receives a pointer to a [`StatorFunctionCallbackInfo`] which
 * provides access to the call arguments and isolate.  It must return either
 * a new [`StatorValue`] (the caller — i.e. the engine wrapper — owns it and
 * frees it automatically) or a null pointer (treated as `undefined`).
 */
typedef struct StatorValue *(*StatorFunctionTemplateCallback)(const struct StatorFunctionCallbackInfo*);

/**
 * C-compatible vtable that embedders fill in to customise engine behaviour.
 *
 * All fields are optional (`Option<…>`).  When a field is `None` the engine
 * falls back to a default (no-op or zero).
 *
 * # Safety requirements for callers
 * Every function pointer, if set, must remain valid for the entire lifetime of
 * the owning [`StatorPlatform`].  Calling [`stator_platform_destroy`] on the
 * platform is the only safe point at which the function pointers may be
 * invalidated.
 */
typedef struct StatorPlatformVTable {
  /**
   * Return the number of worker threads available for background work.
   *
   * May be `None`; in that case the engine defaults to `0`.
   */
  uint32_t (*number_of_worker_threads)(void);
  /**
   * Schedule `task` for execution on a platform thread.
   *
   * The platform takes ownership of `task`.  May be `None` (tasks are
   * silently dropped).
   */
  void (*post_task)(void *task);
  /**
   * Return a monotonically increasing time in seconds.
   *
   * May be `None`; the engine returns `0.0` when unset.
   */
  double (*monotonically_increasing_time)(void);
  /**
   * Return the current wall-clock time in milliseconds since the Unix epoch.
   *
   * May be `None`; the engine returns `0.0` when unset.
   */
  double (*current_clock_time_millis)(void);
} StatorPlatformVTable;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Create a new isolate.
 *
 * The returned pointer must eventually be passed to [`stator_isolate_destroy`]
 * to free all associated resources.  Returns a null pointer on allocation
 * failure (extremely unlikely in practice).
 */
struct StatorIsolate *stator_isolate_create(void);

/**
 * Create a new isolate.
 *
 * This is the preferred spelling for the V8-compatible lifecycle API.
 * Equivalent to [`stator_isolate_create`].  The returned pointer must
 * eventually be passed to [`stator_isolate_dispose`].
 */
struct StatorIsolate *stator_isolate_new(void);

/**
 * Destroy an isolate previously created with [`stator_isolate_create`].
 *
 * After this call the pointer is invalid and must not be used.
 *
 * # Safety
 * - `isolate` must be a non-null pointer returned by `stator_isolate_create`.
 * - `isolate` must not be used again after this call.
 * - This function must not be called more than once for the same pointer.
 */
void stator_isolate_destroy(struct StatorIsolate *isolate);

/**
 * Dispose an isolate previously created with [`stator_isolate_new`].
 *
 * This is the preferred spelling for the V8-compatible lifecycle API.
 * Equivalent to [`stator_isolate_destroy`].
 *
 * # Safety
 * - `isolate` must be a non-null pointer returned by `stator_isolate_new`.
 * - `isolate` must not be used again after this call.
 * - This function must not be called more than once for the same pointer.
 */
void stator_isolate_dispose(struct StatorIsolate *isolate);

/**
 * Mark `isolate` as entered on the current thread.
 *
 * Each call to `stator_isolate_enter` must be balanced by a corresponding
 * call to [`stator_isolate_exit`].  Does nothing when `isolate` is null.
 *
 * # Safety
 * `isolate` must be a non-null, valid pointer to a live [`StatorIsolate`].
 */
void stator_isolate_enter(struct StatorIsolate *isolate);

/**
 * Unmark `isolate` as entered on the current thread.
 *
 * Must be called once for every preceding [`stator_isolate_enter`] call.
 * Does nothing when `isolate` is null.
 *
 * # Safety
 * `isolate` must be a non-null, valid pointer to a live [`StatorIsolate`].
 */
void stator_isolate_exit(struct StatorIsolate *isolate);

/**
 * Store an opaque embedder-defined pointer at `slot` on the isolate.
 *
 * Slots are zero-indexed.  Storing `NULL` at a slot is permitted and
 * equivalent to clearing it.  Does nothing when `isolate` is null.
 *
 * # Safety
 * `isolate` must be a non-null, valid pointer to a live [`StatorIsolate`].
 */
void stator_isolate_set_data(struct StatorIsolate *isolate, uint32_t slot, void *data);

/**
 * Retrieve the embedder-defined pointer previously stored at `slot`.
 *
 * Returns a null pointer when `isolate` is null or `slot` has not been set.
 *
 * # Safety
 * `isolate` must be either null or a valid, live [`StatorIsolate`] pointer.
 */
void *stator_isolate_get_data(const struct StatorIsolate *isolate, uint32_t slot);

/**
 * Record `exception` as the pending exception on `isolate`.
 *
 * At most one pending exception is stored at a time; a subsequent call
 * replaces the previous value.  Does nothing when `isolate` is null.
 *
 * The caller retains ownership of `exception`; the isolate only holds a
 * raw pointer and does not free it.
 *
 * # Safety
 * - `isolate` must be a non-null, valid pointer to a live [`StatorIsolate`].
 * - `exception` must be either null or a valid, live [`StatorValue`] pointer
 *   that outlives the pending-exception window.
 */
void stator_isolate_throw_exception(struct StatorIsolate *isolate, struct StatorValue *exception);

/**
 * Return the context most recently made current on `isolate`.
 *
 * Returns a null pointer when `isolate` is null or no context has been made
 * current (i.e. no context has been created on this isolate yet, or the
 * most recent one was destroyed).
 *
 * # Safety
 * `isolate` must be either null or a valid, live [`StatorIsolate`] pointer.
 */
struct StatorContext *stator_isolate_get_current_context(const struct StatorIsolate *isolate);

/**
 * Trigger a minor (young-generation) garbage collection on the isolate's heap.
 *
 * # Safety
 * `isolate` must be a non-null, valid pointer to a live `StatorIsolate`.
 */
void stator_isolate_gc(struct StatorIsolate *isolate);

/**
 * Fill `*stats` with the current compilation tier statistics.
 *
 * Reports the cumulative number of baseline-JIT-compiled functions and the
 * total machine-code bytes produced on this thread since the process started.
 *
 * On platforms where the baseline JIT is not available all counts will be
 * zero.
 *
 * Does nothing when `stats` is null.
 *
 * # Safety
 * - `isolate` must be either null or a valid, live `StatorIsolate` pointer.
 * - `stats` must be a non-null, properly aligned pointer to a
 *   `StatorCompilationStats` that is valid for writes.
 */
void stator_isolate_get_stats(const struct StatorIsolate *_isolate,
                              struct StatorCompilationStats *stats);

/**
 * Create a new context associated with `isolate`.
 *
 * Returns a null pointer if `isolate` is null.  The caller must eventually
 * pass the returned pointer to [`stator_context_destroy`].
 *
 * Creating a context automatically makes it the current context on `isolate`
 * (equivalent to entering it).  Destroying the context via
 * [`stator_context_destroy`] clears the current-context slot when it matches.
 *
 * # Safety
 * `isolate` must be a non-null, valid pointer to a live [`StatorIsolate`].
 */
struct StatorContext *stator_context_new(struct StatorIsolate *isolate);

/**
 * Destroy a context previously created with [`stator_context_new`].
 *
 * If `ctx` is the current context on its associated isolate, the
 * current-context slot is cleared (set to null).
 *
 * # Safety
 * `ctx` must be a non-null pointer returned by `stator_context_new` and must
 * not be used again after this call.
 */
void stator_context_destroy(struct StatorContext *ctx);

/**
 * Mark `ctx` as entered on the current thread.
 *
 * Each call to `stator_context_enter` must be balanced by a corresponding
 * call to [`stator_context_exit`].  Entering a context also makes it the
 * current context on its associated isolate.  Does nothing when `ctx` is null.
 *
 * # Safety
 * `ctx` must be either null or a valid, live [`StatorContext`] pointer.
 */
void stator_context_enter(struct StatorContext *ctx);

/**
 * Unmark `ctx` as entered on the current thread.
 *
 * Must be called once for every preceding [`stator_context_enter`] call.
 * When the enter count reaches zero the context is no longer recorded as
 * current on its associated isolate.  Does nothing when `ctx` is null.
 *
 * # Safety
 * `ctx` must be either null or a valid, live [`StatorContext`] pointer.
 */
void stator_context_exit(struct StatorContext *ctx);

/**
 * Return a non-owning pointer to the global object of `ctx`.
 *
 * The returned pointer is valid for as long as `ctx` is alive.  **The caller
 * must not pass the returned pointer to [`stator_object_destroy`]**; the
 * global object is owned by the context and is freed when the context is
 * destroyed via [`stator_context_destroy`].
 *
 * Returns a null pointer when `ctx` is null.
 *
 * # Safety
 * `ctx` must be either null or a valid, live [`StatorContext`] pointer.
 */
struct StatorObject *stator_context_global(struct StatorContext *ctx);

/**
 * Create a new number value.
 *
 * Returns a null pointer if `isolate` is null.
 *
 * # Safety
 * `isolate` must be a non-null, valid pointer to a live [`StatorIsolate`].
 */
struct StatorValue *stator_value_new_number(struct StatorIsolate *isolate, double val);

/**
 * Create a new string value from a buffer of `len` bytes.
 *
 * `data` need not be null-terminated; `len` bytes are copied.  Any embedded
 * null bytes are replaced by truncating at the first null.  Returns a null
 * pointer if `isolate` or `data` is null.
 *
 * # Safety
 * - `isolate` must be a non-null, valid pointer to a live [`StatorIsolate`].
 * - `data` must be valid for reads of `len` bytes.
 */
struct StatorValue *stator_value_new_string(struct StatorIsolate *isolate,
                                            const char *data,
                                            size_t len);

/**
 * Create a new boolean value.
 *
 * Returns a null pointer if `isolate` is null.
 *
 * # Safety
 * `isolate` must be a non-null, valid pointer to a live [`StatorIsolate`].
 */
struct StatorValue *stator_value_new_boolean(struct StatorIsolate *isolate, bool val);

/**
 * Create a new `undefined` value.
 *
 * Returns a null pointer if `isolate` is null.
 *
 * # Safety
 * `isolate` must be a non-null, valid pointer to a live [`StatorIsolate`].
 */
struct StatorValue *stator_value_new_undefined(struct StatorIsolate *isolate);

/**
 * Create a new `null` value.
 *
 * Returns a null pointer if `isolate` is null.
 *
 * # Safety
 * `isolate` must be a non-null, valid pointer to a live [`StatorIsolate`].
 */
struct StatorValue *stator_value_new_null(struct StatorIsolate *isolate);

/**
 * Create a new plain-object value.
 *
 * Returns a null pointer if `isolate` is null.
 *
 * # Safety
 * `isolate` must be a non-null, valid pointer to a live [`StatorIsolate`].
 */
struct StatorValue *stator_value_new_object(struct StatorIsolate *isolate);

/**
 * Create a new function-tagged value.
 *
 * Returns a null pointer if `isolate` is null.
 *
 * # Safety
 * `isolate` must be a non-null, valid pointer to a live [`StatorIsolate`].
 */
struct StatorValue *stator_value_new_function_tag(struct StatorIsolate *isolate);

/**
 * Create a new array-tagged value.
 *
 * Returns a null pointer if `isolate` is null.
 *
 * # Safety
 * `isolate` must be a non-null, valid pointer to a live [`StatorIsolate`].
 */
struct StatorValue *stator_value_new_array_tag(struct StatorIsolate *isolate);

/**
 * Create a new `Date`-tagged value.
 *
 * Returns a null pointer if `isolate` is null.
 *
 * # Safety
 * `isolate` must be a non-null, valid pointer to a live [`StatorIsolate`].
 */
struct StatorValue *stator_value_new_date_tag(struct StatorIsolate *isolate);

/**
 * Create a new `RegExp`-tagged value.
 *
 * Returns a null pointer if `isolate` is null.
 *
 * # Safety
 * `isolate` must be a non-null, valid pointer to a live [`StatorIsolate`].
 */
struct StatorValue *stator_value_new_regexp_tag(struct StatorIsolate *isolate);

/**
 * Create a new `Promise`-tagged value.
 *
 * Returns a null pointer if `isolate` is null.
 *
 * # Safety
 * `isolate` must be a non-null, valid pointer to a live [`StatorIsolate`].
 */
struct StatorValue *stator_value_new_promise_tag(struct StatorIsolate *isolate);

/**
 * Create a new `Map`-tagged value.
 *
 * Returns a null pointer if `isolate` is null.
 *
 * # Safety
 * `isolate` must be a non-null, valid pointer to a live [`StatorIsolate`].
 */
struct StatorValue *stator_value_new_map_tag(struct StatorIsolate *isolate);

/**
 * Create a new `Set`-tagged value.
 *
 * Returns a null pointer if `isolate` is null.
 *
 * # Safety
 * `isolate` must be a non-null, valid pointer to a live [`StatorIsolate`].
 */
struct StatorValue *stator_value_new_set_tag(struct StatorIsolate *isolate);

/**
 * Create a new string value from a UTF-8 byte buffer of `len` bytes.
 *
 * This is the V8-style spelling of [`stator_value_new_string`].  `data` need
 * not be null-terminated; `len` bytes are copied.  Any embedded null bytes
 * cause the string to be truncated at the first such byte.  Returns a null
 * pointer if `isolate` or `data` is null.
 *
 * # Safety
 * - `isolate` must be a non-null, valid pointer to a live [`StatorIsolate`].
 * - `data` must be valid for reads of `len` bytes and must point to valid
 *   UTF-8 data.
 */
struct StatorValue *stator_string_new_from_utf8(struct StatorIsolate *isolate,
                                                const char *data,
                                                size_t len);

/**
 * Return the number of UTF-8 bytes required to represent `val`.
 *
 * Returns `0` when `val` is null or not a string.  The returned length does
 * **not** include a terminating null byte.
 *
 * # Safety
 * `val` must be either null or a valid, live [`StatorValue`] pointer.
 */
size_t stator_string_utf8_length(const struct StatorValue *val);

/**
 * Write the UTF-8 representation of `val` into `buf`.
 *
 * At most `buf_size` bytes are written.  The output is **not**
 * null-terminated (unlike `stator_value_as_string`).  If `nchars_ref` is
 * non-null, `*nchars_ref` is set to the number of bytes written.  Returns
 * the number of bytes written, or `0` when `val` is null or not a string or
 * `buf` is null.
 *
 * # Safety
 * - `val` must be either null or a valid, live [`StatorValue`] pointer.
 * - `buf` must be valid for writes of `buf_size` bytes (unless null).
 * - `nchars_ref` must be either null or a valid pointer to a `usize`.
 */
size_t stator_string_write_utf8(const struct StatorValue *val,
                                char *buf,
                                size_t buf_size,
                                size_t *nchars_ref);

/**
 * Create a new number value (V8-style spelling of [`stator_value_new_number`]).
 *
 * Returns a null pointer if `isolate` is null.
 *
 * # Safety
 * `isolate` must be a non-null, valid pointer to a live [`StatorIsolate`].
 */
struct StatorValue *stator_number_new(struct StatorIsolate *isolate, double val);

/**
 * Create a new integer value from a signed 64-bit integer.
 *
 * The value is stored as an ECMAScript `Number` (IEEE 754 double).  Values
 * outside the safe-integer range (`±2⁵³−1`) may lose precision.  Returns a
 * null pointer if `isolate` is null.
 *
 * # Safety
 * `isolate` must be a non-null, valid pointer to a live [`StatorIsolate`].
 */
struct StatorValue *stator_integer_new(struct StatorIsolate *isolate, int64_t val);

/**
 * Create a new boolean value (V8-style spelling of [`stator_value_new_boolean`]).
 *
 * Returns a null pointer if `isolate` is null.
 *
 * # Safety
 * `isolate` must be a non-null, valid pointer to a live [`StatorIsolate`].
 */
struct StatorValue *stator_boolean_new(struct StatorIsolate *isolate, bool val);

/**
 * Create a new `undefined` value (V8-style spelling of [`stator_value_new_undefined`]).
 *
 * Returns a null pointer if `isolate` is null.
 *
 * # Safety
 * `isolate` must be a non-null, valid pointer to a live [`StatorIsolate`].
 */
struct StatorValue *stator_undefined_new(struct StatorIsolate *isolate);

/**
 * Create a new `null` value (V8-style spelling of [`stator_value_new_null`]).
 *
 * Returns a null pointer if `isolate` is null.
 *
 * # Safety
 * `isolate` must be a non-null, valid pointer to a live [`StatorIsolate`].
 */
struct StatorValue *stator_null_new(struct StatorIsolate *isolate);

/**
 * Destroy a value and decrement the isolate's live-object counter.
 *
 * # Safety
 * `val` must be a non-null pointer returned by any `stator_value_new_*`
 * function and must not be used again after this call.
 */
void stator_value_destroy(struct StatorValue *val);

/**
 * Return a static C string describing the type of `val`: `"number"` or
 * `"string"`.
 *
 * Returns `"undefined"` when `val` is null.  The returned pointer is valid
 * for the lifetime of the process.
 *
 * # Safety
 * `val` must be either null or a valid, live [`StatorValue`] pointer.
 */
const char *stator_value_type(const struct StatorValue *val);

/**
 * Return the numeric value stored in `val`, or `NaN` if `val` is null or not
 * a number.
 *
 * # Safety
 * `val` must be either null or a valid, live [`StatorValue`] pointer.
 */
double stator_value_as_number(const struct StatorValue *val);

/**
 * Return a null-terminated C string for the string stored in `val`.
 *
 * Returns a pointer to an empty string (`""`) when `val` is null or not a
 * string.  The pointer is valid only as long as `val` is alive.
 *
 * # Safety
 * `val` must be either null or a valid, live [`StatorValue`] pointer.
 */
const char *stator_value_as_string(const struct StatorValue *val);

/**
 * Returns `true` if `val` is the ECMAScript `undefined` value.
 *
 * A null `val` pointer is treated as `undefined` and also returns `true`.
 *
 * # Safety
 * `val` must be either null or a valid, live [`StatorValue`] pointer.
 */
bool stator_value_is_undefined(const struct StatorValue *val);

/**
 * Returns `true` if `val` is the ECMAScript `null` value.
 *
 * # Safety
 * `val` must be either null or a valid, live [`StatorValue`] pointer.
 */
bool stator_value_is_null(const struct StatorValue *val);

/**
 * Returns `true` if `val` holds a JavaScript string.
 *
 * # Safety
 * `val` must be either null or a valid, live [`StatorValue`] pointer.
 */
bool stator_value_is_string(const struct StatorValue *val);

/**
 * Returns `true` if `val` holds a JavaScript number.
 *
 * # Safety
 * `val` must be either null or a valid, live [`StatorValue`] pointer.
 */
bool stator_value_is_number(const struct StatorValue *val);

/**
 * Returns `true` if `val` holds a JavaScript boolean.
 *
 * # Safety
 * `val` must be either null or a valid, live [`StatorValue`] pointer.
 */
bool stator_value_is_boolean(const struct StatorValue *val);

/**
 * Returns `true` if `val` is a JavaScript object (excludes `null`).
 *
 * Arrays, dates, regexps, promises, maps, and sets are all objects in
 * ECMAScript and therefore also return `true`.
 *
 * # Safety
 * `val` must be either null or a valid, live [`StatorValue`] pointer.
 */
bool stator_value_is_object(const struct StatorValue *val);

/**
 * Returns `true` if `val` is a callable JavaScript function.
 *
 * # Safety
 * `val` must be either null or a valid, live [`StatorValue`] pointer.
 */
bool stator_value_is_function(const struct StatorValue *val);

/**
 * Returns `true` if `val` is a JavaScript array.
 *
 * # Safety
 * `val` must be either null or a valid, live [`StatorValue`] pointer.
 */
bool stator_value_is_array(const struct StatorValue *val);

/**
 * Returns `true` if `val` is a number whose value is a signed 32-bit integer.
 *
 * A value is considered an int32 when it is a finite number equal to its own
 * `ToInt32` conversion: i.e. it is an integer in the range `[−2³¹, 2³¹−1]`.
 *
 * # Safety
 * `val` must be either null or a valid, live [`StatorValue`] pointer.
 */
bool stator_value_is_int32(const struct StatorValue *val);

/**
 * Returns `true` if `val` is a number whose value is an unsigned 32-bit integer.
 *
 * A value is considered a uint32 when it is a finite number equal to its own
 * `ToUint32` conversion: i.e. it is an integer in the range `[0, 2³²−1]`.
 *
 * # Safety
 * `val` must be either null or a valid, live [`StatorValue`] pointer.
 */
bool stator_value_is_uint32(const struct StatorValue *val);

/**
 * Returns `true` if `val` is a JavaScript `Date` object.
 *
 * # Safety
 * `val` must be either null or a valid, live [`StatorValue`] pointer.
 */
bool stator_value_is_date(const struct StatorValue *val);

/**
 * Returns `true` if `val` is a JavaScript `RegExp` object.
 *
 * # Safety
 * `val` must be either null or a valid, live [`StatorValue`] pointer.
 */
bool stator_value_is_regexp(const struct StatorValue *val);

/**
 * Returns `true` if `val` is a JavaScript `Promise` object.
 *
 * # Safety
 * `val` must be either null or a valid, live [`StatorValue`] pointer.
 */
bool stator_value_is_promise(const struct StatorValue *val);

/**
 * Returns `true` if `val` is a JavaScript `Map` object.
 *
 * # Safety
 * `val` must be either null or a valid, live [`StatorValue`] pointer.
 */
bool stator_value_is_map(const struct StatorValue *val);

/**
 * Returns `true` if `val` is a JavaScript `Set` object.
 *
 * # Safety
 * `val` must be either null or a valid, live [`StatorValue`] pointer.
 */
bool stator_value_is_set(const struct StatorValue *val);

/**
 * Create a new, empty JavaScript object.
 *
 * Returns a null pointer if `isolate` is null.
 *
 * # Safety
 * `isolate` must be a non-null, valid pointer to a live [`StatorIsolate`].
 */
struct StatorObject *stator_object_new(struct StatorIsolate *isolate);

/**
 * Destroy an object and decrement the isolate's live-object counter.
 *
 * # Safety
 * `obj` must be a non-null pointer returned by `stator_object_new` and must
 * not be used again after this call.
 */
void stator_object_destroy(struct StatorObject *obj);

/**
 * Set (or overwrite) the named property `key` on `obj` to `val`.
 *
 * The value is copied by value into the object; the caller retains ownership
 * of `val` and must destroy it independently.  Does nothing if any argument
 * is null.
 *
 * # Safety
 * - `obj` must be a valid, live [`StatorObject`] pointer.
 * - `key` must be a valid, null-terminated C string.
 * - `val` must be a valid, live [`StatorValue`] pointer.
 */
void stator_object_set(struct StatorObject *obj, const char *key, const struct StatorValue *val);

/**
 * Get the named property `key` from `obj` as a new [`StatorValue`].
 *
 * Returns a null pointer if `obj` or `key` is null, or if the property does
 * not exist.  The caller owns the returned pointer and must pass it to
 * [`stator_value_destroy`].
 *
 * # Safety
 * - `obj` must be a valid, live [`StatorObject`] pointer.
 * - `key` must be a valid, null-terminated C string.
 */
struct StatorValue *stator_object_get(const struct StatorObject *obj, const char *key);

/**
 * Return `true` if `obj` has a property with the given `key` (own or
 * inherited via the prototype chain).
 *
 * Returns `false` if any argument is null.
 *
 * # Safety
 * - `obj` must be a valid, live [`StatorObject`] pointer.
 * - `key` must be a valid, null-terminated C string.
 */
bool stator_object_has(const struct StatorObject *obj, const char *key);

/**
 * Delete the named property `key` from `obj`.
 *
 * Returns `true` if the property was successfully deleted (or did not exist),
 * `false` if the deletion fails (e.g. the property is non-configurable, the
 * object is non-extensible in a way that prevents deletion, or any argument
 * is null).
 *
 * # Safety
 * - `obj` must be a valid, live [`StatorObject`] pointer.
 * - `key` must be a valid, null-terminated C string.
 */
bool stator_object_delete(struct StatorObject *obj, const char *key);

/**
 * Collect the own enumerable property names of `obj` into a new
 * [`StatorPropertyNames`] snapshot.
 *
 * Returns a null pointer if `obj` is null.  The caller must eventually pass
 * the returned pointer to [`stator_property_names_destroy`].
 *
 * # Safety
 * `obj` must be a valid, live [`StatorObject`] pointer.
 */
struct StatorPropertyNames *stator_object_get_property_names(const struct StatorObject *obj);

/**
 * Return the number of property names in `names`.
 *
 * Returns `0` if `names` is null.
 *
 * # Safety
 * `names` must be either null or a valid, live [`StatorPropertyNames`] pointer.
 */
size_t stator_property_names_count(const struct StatorPropertyNames *names);

/**
 * Return a pointer to the null-terminated property name at position `index`.
 *
 * The returned pointer is valid for as long as `names` is alive and has not
 * been destroyed.  Returns a null pointer if `names` is null or `index` is
 * out of range.
 *
 * # Safety
 * `names` must be either null or a valid, live [`StatorPropertyNames`] pointer.
 */
const char *stator_property_names_get(const struct StatorPropertyNames *names, size_t index);

/**
 * Destroy a [`StatorPropertyNames`] snapshot previously returned by
 * [`stator_object_get_property_names`].
 *
 * After this call the pointer and all name pointers obtained from it are
 * invalid and must not be used.
 *
 * # Safety
 * `names` must be a non-null pointer returned by
 * `stator_object_get_property_names` and must not be used again after this
 * call.
 */
void stator_property_names_destroy(struct StatorPropertyNames *names);

/**
 * Trigger a minor (young-generation) GC on the isolate heap.
 *
 * This is the preferred spelling for embedders using the Phase 1 object
 * model; it is equivalent to [`stator_isolate_gc`].
 *
 * # Safety
 * `isolate` must be a non-null, valid pointer to a live [`StatorIsolate`].
 */
void stator_gc_collect(struct StatorIsolate *isolate);

/**
 * Return the number of live embedder-owned handles (values + objects) that
 * have been created on `isolate` but not yet destroyed.
 *
 * After a GC cycle this count reflects how many objects would survive because
 * they are still reachable through live handles.
 *
 * Returns 0 when `isolate` is null.
 *
 * # Safety
 * `isolate` must be either null or a valid, live [`StatorIsolate`] pointer.
 */
size_t stator_live_object_count(const struct StatorIsolate *isolate);

/**
 * Return the number of bytes currently allocated in the young-generation
 * from-space.  This is 0 immediately after a GC cycle.
 *
 * Returns 0 when `isolate` is null.
 *
 * # Safety
 * `isolate` must be either null or a valid, live [`StatorIsolate`] pointer.
 */
size_t stator_heap_used(const struct StatorIsolate *isolate);

/**
 * Return the total capacity (in bytes) of the young-generation semi-space,
 * counting both the from-space and to-space halves.
 *
 * Returns 0 when `isolate` is null.
 *
 * # Safety
 * `isolate` must be either null or a valid, live [`StatorIsolate`] pointer.
 */
size_t stator_heap_capacity(const struct StatorIsolate *isolate);

/**
 * Compile `source` (a UTF-8 string of `source_len` bytes) into bytecode.
 *
 * Returns a non-null [`StatorScript`] pointer in all cases (even on error).
 * Call [`stator_script_get_error`] to check whether compilation succeeded.
 * The caller must eventually pass the returned pointer to
 * [`stator_script_free`].
 *
 * Returns a null pointer only on an internal allocation failure (extremely
 * unlikely in practice).
 *
 * # Safety
 * - `ctx` must be either null or a valid, live [`StatorContext`] pointer.
 * - `source` must be valid for reads of `source_len` bytes of valid UTF-8.
 */
struct StatorScript *stator_script_compile(struct StatorContext *_ctx,
                                           const char *source,
                                           size_t source_len);

/**
 * Return a null-terminated error message if `script` compiled with an error.
 *
 * Returns a null pointer when `script` compiled successfully.  The returned
 * pointer is valid as long as `script` is alive (i.e. until
 * [`stator_script_free`] is called).
 *
 * # Safety
 * `script` must be a non-null pointer returned by [`stator_script_compile`].
 */
const char *stator_script_get_error(const struct StatorScript *script);

/**
 * Print the decoded bytecode listing for `script` to standard output.
 *
 * Each instruction is printed on a new line in the form:
 * `  <OpcodeName> [<operand>, …]`
 *
 * Does nothing if `script` is null or compiled with an error.
 *
 * # Safety
 * `script` must be either null or a valid, live [`StatorScript`] pointer.
 */
void stator_bytecode_dump(const struct StatorScript *script);

/**
 * Return the number of bytecode instructions in a successfully compiled script.
 *
 * Returns 0 if `script` is null, compiled with an error, or the bytecode
 * stream cannot be decoded.
 *
 * # Safety
 * `script` must be either null or a valid, live [`StatorScript`] pointer.
 */
size_t stator_script_bytecode_count(const struct StatorScript *script);

/**
 * Free a [`StatorScript`] previously returned by [`stator_script_compile`].
 *
 * # Safety
 * `script` must be a non-null pointer returned by [`stator_script_compile`]
 * and must not be used again after this call.
 */
void stator_script_free(struct StatorScript *script);

/**
 * Execute a compiled script in `ctx` and return the result as a
 * [`StatorValue`].
 *
 * The script must have been successfully compiled (i.e.
 * [`stator_script_get_error`] returns null).  If the script produces an
 * exception the call returns null.
 *
 * The caller must pass the returned pointer to [`stator_value_destroy`] when
 * done, or ignore a null return.
 *
 * # Safety
 * - `script` must be a non-null pointer returned by [`stator_script_compile`].
 * - `ctx` must be a valid, live [`StatorContext`] pointer, or null (in which
 *   case an empty global environment is used).
 */
struct StatorValue *stator_script_run(const struct StatorScript *script, struct StatorContext *ctx);

/**
 * Convert the value `val` to a UTF-8 string and write it into `buf`.
 *
 * At most `buf_len` bytes (including the NUL terminator) are written.
 * Returns the number of bytes written **excluding** the NUL terminator, or
 * `-1` on error.  Returns `0` when `val` is null (writes `""` and a NUL).
 *
 * # Safety
 * - `val` must be either null or a valid, live [`StatorValue`] pointer.
 * - `buf` must be valid for writes of `buf_len` bytes, or null when
 *   `buf_len` is 0 (in which case only the required length is returned).
 */
int32_t stator_value_to_string_utf8(const struct StatorValue *val, char *buf, size_t buf_len);

/**
 * Coerce `val` to a number following ECMAScript §7.1.4 **ToNumber**.
 *
 * | Value type | Result |
 * |---|---|
 * | `undefined` (or null pointer) | `NaN` |
 * | `null` | `+0` |
 * | `true` | `1` |
 * | `false` | `+0` |
 * | number | the number itself |
 * | string | parsed numeric value; `NaN` if unparseable |
 * | object / function / … | `NaN` |
 *
 * # Safety
 * `val` must be either null or a valid, live [`StatorValue`] pointer.
 */
double stator_value_to_number(const struct StatorValue *val);

/**
 * Coerce `val` to a string following ECMAScript §7.1.17 **ToString** and
 * return it as a new [`StatorValue`] of string type.
 *
 * The caller owns the returned pointer and must pass it to
 * [`stator_value_destroy`] (or let a handle scope manage it).
 *
 * Returns a null pointer if `isolate` is null.
 *
 * # Safety
 * - `isolate` must be a non-null, valid pointer to a live [`StatorIsolate`].
 * - `val` must be either null or a valid, live [`StatorValue`] pointer.
 */
struct StatorValue *stator_value_to_string(struct StatorIsolate *isolate,
                                           const struct StatorValue *val);

/**
 * Coerce `val` to a signed 32-bit integer following ECMAScript §7.1.7
 * **ToInt32**.
 *
 * Applies `ToNumber` first, then reduces modulo 2³² and maps to the signed
 * range `[−2³¹, 2³¹−1]`.  `NaN`, `±0`, and `±Infinity` all convert to `0`.
 *
 * Returns `0` when `val` is null.
 *
 * # Safety
 * `val` must be either null or a valid, live [`StatorValue`] pointer.
 */
int32_t stator_value_to_int32(const struct StatorValue *val);

/**
 * Coerce `val` to an unsigned 32-bit integer following ECMAScript §7.1.8
 * **ToUint32**.
 *
 * Applies `ToNumber` first, then reduces modulo 2³².  `NaN`, `±0`, and
 * `±Infinity` all convert to `0`.
 *
 * Returns `0` when `val` is null.
 *
 * # Safety
 * `val` must be either null or a valid, live [`StatorValue`] pointer.
 */
uint32_t stator_value_to_uint32(const struct StatorValue *val);

/**
 * Coerce `val` to a boolean following ECMAScript §7.1.2 **ToBoolean**.
 *
 * Falsy values: `undefined`, `null`, `false`, `+0`, `-0`, `NaN`, `""`.
 * Everything else is truthy.  A null pointer is treated as `undefined` and
 * returns `false`.
 *
 * # Safety
 * `val` must be either null or a valid, live [`StatorValue`] pointer.
 */
bool stator_value_to_boolean(const struct StatorValue *val);

/**
 * Test whether `a === b` following ECMAScript §7.2.15 **IsStrictlyEqual**.
 *
 * Rules:
 * - Different types → `false`.
 * - `undefined === undefined` → `true`.
 * - `null === null` → `true`.
 * - Numbers: `NaN !== NaN`; `+0 === -0`.
 * - Strings: byte-for-byte equality.
 * - Booleans: value equality.
 * - Object / function / array / … : `false` (no shared identity in FFI
 *   handles; two distinct handles are never the same object).
 *
 * Both null pointers are treated as `undefined`.
 *
 * # Safety
 * `a` and `b` must each be either null or a valid, live [`StatorValue`]
 * pointer.
 */
bool stator_value_strict_equals(const struct StatorValue *a, const struct StatorValue *b);

/**
 * Register a native function named `name` on `ctx`.
 *
 * After registration, JavaScript code running via [`stator_script_run`] can
 * call `name(…)` as a global function.  The C `callback` is invoked with the
 * active context, an array of argument pointers (valid only for the duration
 * of the call), and the argument count.
 *
 * The name `"console"` has special semantics: if not yet defined it creates a
 * plain object; the function is then installed as `console.<method>` where
 * `<method>` is derived from the dot notation in `name`.  For example,
 * `name = "console.log"` registers `log` on the `console` object.
 *
 * Does nothing when `ctx` or `name` is null.
 *
 * # Safety
 * - `ctx` must be a valid, live [`StatorContext`] pointer.
 * - `name` must be a valid, null-terminated C string.
 * - `callback` must remain callable for the lifetime of `ctx`.
 */
void stator_register_native_function(struct StatorContext *ctx,
                                     const char *name,
                                     StatorNativeCallback callback);

/**
 * Return the number of arguments passed to this call.
 *
 * Returns `0` when `info` is null.
 *
 * # Safety
 * `info` must be either null or a valid pointer to a live
 * [`StatorFunctionCallbackInfo`].
 */
int32_t stator_function_callback_info_length(const struct StatorFunctionCallbackInfo *info);

/**
 * Return a pointer to the argument at position `index`.
 *
 * The returned pointer is valid only for the duration of the callback
 * invocation.  Returns a null pointer if `info` is null or `index` is out of
 * range.
 *
 * # Safety
 * `info` must be either null or a valid pointer to a live
 * [`StatorFunctionCallbackInfo`].
 */
const struct StatorValue *stator_function_callback_info_get(const struct StatorFunctionCallbackInfo *info,
                                                            int32_t index);

/**
 * Return the isolate associated with this call.
 *
 * Returns a null pointer if `info` is null.
 *
 * # Safety
 * `info` must be either null or a valid pointer to a live
 * [`StatorFunctionCallbackInfo`].
 */
struct StatorIsolate *stator_function_callback_info_get_isolate(const struct StatorFunctionCallbackInfo *info);

/**
 * Create a new function template associated with `isolate`.
 *
 * Returns a null pointer if `isolate` is null.  The caller must eventually
 * pass the returned pointer to [`stator_function_template_destroy`].
 *
 * # Safety
 * - `isolate` must be a non-null, valid pointer to a live [`StatorIsolate`].
 * - `callback` must remain valid for the lifetime of the template.
 */
struct StatorFunctionTemplate *stator_function_template_new(struct StatorIsolate *isolate,
                                                            StatorFunctionTemplateCallback callback);

/**
 * Destroy a function template previously created with
 * [`stator_function_template_new`].
 *
 * Does nothing if `tmpl` is null.
 *
 * # Safety
 * `tmpl` must be a non-null pointer returned by
 * [`stator_function_template_new`] and must not be used again after this call.
 */
void stator_function_template_destroy(struct StatorFunctionTemplate *tmpl);

/**
 * Produce a [`StatorValue`] representing the function described by `tmpl`.
 *
 * The returned value has type `"function"` and can be installed into a
 * context's global environment via [`stator_context_global_set`], after which
 * JavaScript code run with [`stator_script_run`] can call it as a global
 * function.
 *
 * Returns a null pointer if `tmpl` is null.  The caller owns the returned
 * pointer and must eventually pass it to [`stator_value_destroy`] (or let a
 * handle scope manage it).
 *
 * # Safety
 * `tmpl` must be either null or a valid, live [`StatorFunctionTemplate`]
 * pointer.
 */
struct StatorValue *stator_function_template_get_function(const struct StatorFunctionTemplate *tmpl,
                                                          struct StatorContext *_ctx);

/**
 * Install a value into the context's global environment under `name`.
 *
 * After this call, JavaScript code running via [`stator_script_run`] can
 * reference `name` as a global variable.  For function values (created via
 * [`stator_function_template_get_function`] or
 * [`stator_value_new_*`][stator_value_new_number]), the callable is installed
 * so that scripts can invoke it.
 *
 * Does nothing if `ctx` or `name` is null.  A null `val` installs
 * `undefined`.
 *
 * # Safety
 * - `ctx` must be a valid, live [`StatorContext`] pointer.
 * - `name` must be a valid, null-terminated C string.
 * - `val` must be either null or a valid, live [`StatorValue`] pointer.
 */
void stator_context_global_set(struct StatorContext *ctx,
                               const char *name,
                               const struct StatorValue *val);

/**
 * Open a new handle scope on `isolate`.
 *
 * All [`StatorValue`] handles created after this call (and before the
 * corresponding [`stator_handle_scope_close`]) are owned by the returned
 * scope and will be destroyed automatically when the scope is closed.
 *
 * Returns a null pointer if `isolate` is null.  The caller must eventually
 * pass the returned pointer to [`stator_handle_scope_close`].
 *
 * # Safety
 * `isolate` must be a non-null, valid pointer to a live [`StatorIsolate`].
 */
struct StatorHandleScope *stator_handle_scope_new(struct StatorIsolate *isolate);

/**
 * Close a handle scope and destroy all values registered with it.
 *
 * After this call, all [`StatorValue`] pointers that were created while
 * `scope` was the active scope are invalid.  The previous scope (if any) is
 * restored as the active scope on the isolate.
 *
 * Does nothing if `scope` is null.
 *
 * # Safety
 * - `scope` must be a non-null pointer returned by [`stator_handle_scope_new`].
 * - `scope` must be the *innermost* open scope on its isolate (i.e. handle
 *   scopes must be closed in LIFO order).
 * - `scope` must not be used again after this call.
 */
void stator_handle_scope_close(struct StatorHandleScope *scope);

/**
 * Open a new escapable handle scope on `isolate`.
 *
 * Returns a null pointer if `isolate` is null.  The caller must eventually
 * pass the returned pointer to [`stator_escapable_handle_scope_close`].
 *
 * # Safety
 * `isolate` must be a non-null, valid pointer to a live [`StatorIsolate`].
 */
struct StatorEscapableHandleScope *stator_escapable_handle_scope_new(struct StatorIsolate *isolate);

/**
 * Escape `val` from `scope`, promoting it into the enclosing scope.
 *
 * Removes `val` from `scope`'s tracked handles (so it will not be destroyed
 * when the scope is closed) and, if there is an enclosing scope, registers
 * it there.  If there is no enclosing scope the caller takes ownership and
 * must eventually pass `val` to [`stator_value_destroy`].
 *
 * Returns `val` unchanged (for convenient chaining in C/C++ callers), or a
 * null pointer if `scope` or `val` is null.
 *
 * # Safety
 * - `scope` must be a non-null, valid pointer to a live
 *   [`StatorEscapableHandleScope`].
 * - `val` must be a non-null pointer that is currently registered with
 *   `scope` (i.e. it was created while `scope` was the active scope).
 * - Each value may only be escaped once.
 */
struct StatorValue *stator_escapable_handle_scope_escape(struct StatorEscapableHandleScope *scope,
                                                         struct StatorValue *val);

/**
 * Close an escapable handle scope and destroy all non-escaped values.
 *
 * Equivalent in behaviour to [`stator_handle_scope_close`] for the escapable
 * variant.
 *
 * # Safety
 * - `scope` must be a non-null pointer returned by
 *   [`stator_escapable_handle_scope_new`].
 * - `scope` must be the innermost open scope on its isolate.
 * - `scope` must not be used again after this call.
 */
void stator_escapable_handle_scope_close(struct StatorEscapableHandleScope *scope);

/**
 * Create a new platform from an embedder-supplied vtable.
 *
 * The vtable is copied by value; the caller does not need to keep the
 * original `StatorPlatformVTable` alive after this call returns.
 *
 * Returns a null pointer if `vtable` is null.  The caller must eventually
 * pass the returned pointer to [`stator_platform_destroy`].
 *
 * # Safety
 * - `vtable` must be either null or a valid, readable pointer to a
 *   [`StatorPlatformVTable`].
 * - All non-null function pointers stored in the vtable must remain callable
 *   for the entire lifetime of the returned [`StatorPlatform`].
 */
struct StatorPlatform *stator_platform_new(const struct StatorPlatformVTable *vtable);

/**
 * Destroy a platform previously created with [`stator_platform_new`].
 *
 * After this call the pointer is invalid and must not be used.
 *
 * # Safety
 * - `platform` must be a non-null pointer returned by `stator_platform_new`.
 * - `platform` must not be used again after this call.
 * - This function must not be called more than once for the same pointer.
 */
void stator_platform_destroy(struct StatorPlatform *platform);

/**
 * Return the number of worker threads reported by `platform`.
 *
 * Returns `0` when `platform` is null or the vtable entry was not set.
 *
 * # Safety
 * `platform` must be either null or a valid, live [`StatorPlatform`] pointer.
 */
uint32_t stator_platform_number_of_worker_threads(const struct StatorPlatform *platform);

/**
 * Schedule `task` for execution on `platform`.
 *
 * Does nothing when `platform` is null, `task` is null, or the vtable entry
 * was not set.
 *
 * # Safety
 * - `platform` must be either null or a valid, live [`StatorPlatform`] pointer.
 * - `task` must be a non-null pointer whose lifetime the caller manages;
 *   ownership of `task` is transferred to the platform on this call.
 */
void stator_platform_post_task(const struct StatorPlatform *platform, void *task);

/**
 * Return the monotonically increasing time (seconds) from `platform`.
 *
 * Returns `0.0` when `platform` is null or the vtable entry was not set.
 *
 * # Safety
 * `platform` must be either null or a valid, live [`StatorPlatform`] pointer.
 */
double stator_platform_monotonically_increasing_time(const struct StatorPlatform *platform);

/**
 * Return the current clock time in milliseconds from `platform`.
 *
 * Returns `0.0` when `platform` is null or the vtable entry was not set.
 *
 * # Safety
 * `platform` must be either null or a valid, live [`StatorPlatform`] pointer.
 */
double stator_platform_current_clock_time_millis(const struct StatorPlatform *platform);

/**
 * Compile a WebAssembly binary into a [`StatorWasmModule`].
 *
 * Returns a null pointer if `isolate` or `bytes` is null, `len` is zero, or
 * if the bytes do not represent a valid WebAssembly module.
 *
 * The returned pointer must eventually be passed to
 * [`stator_wasm_module_destroy`] to free all associated resources.
 *
 * # Safety
 * - `isolate` must be a non-null, valid pointer to a live [`StatorIsolate`].
 * - `bytes` must be valid for reads of `len` bytes.
 */
struct StatorWasmModule *stator_wasm_compile(struct StatorIsolate *isolate,
                                             const uint8_t *bytes,
                                             size_t len);

/**
 * Free a [`StatorWasmModule`] previously returned by [`stator_wasm_compile`].
 *
 * Does nothing when `module` is null.
 *
 * # Safety
 * `module` must be either null or a valid pointer returned by
 * [`stator_wasm_compile`] that has not been freed yet.
 */
void stator_wasm_module_destroy(struct StatorWasmModule *module);

/**
 * Instantiate a compiled [`StatorWasmModule`] into a live
 * [`StatorWasmInstance`].
 *
 * `ctx` is accepted for future use and may be null.  `imports` is reserved for
 * future use and **must** be null; passing a non-null value is currently
 * ignored.
 *
 * Returns a null pointer if `module` is null or if instantiation fails (e.g.
 * the module requires imports that are not provided).
 *
 * The returned pointer must eventually be passed to
 * [`stator_wasm_instance_destroy`].
 *
 * # Safety
 * - `module` must be a non-null, valid pointer to a live
 *   [`StatorWasmModule`].
 * - `ctx` must be either null or a valid, live [`StatorContext`] pointer.
 * - `imports` must be null.
 */
struct StatorWasmInstance *stator_wasm_instantiate(struct StatorWasmModule *module,
                                                   struct StatorContext *_ctx,
                                                   const void *_imports);

/**
 * Free a [`StatorWasmInstance`] previously returned by
 * [`stator_wasm_instantiate`].
 *
 * Does nothing when `instance` is null.
 *
 * # Safety
 * `instance` must be either null or a valid pointer returned by
 * [`stator_wasm_instantiate`] that has not been freed yet.
 */
void stator_wasm_instance_destroy(struct StatorWasmInstance *instance);

/**
 * Return a null-terminated array of export names from `instance`.
 *
 * Each element in the array is a heap-allocated, null-terminated UTF-8 string.
 * The array itself is terminated by a null pointer.  The caller owns the
 * returned array and must free it with [`stator_wasm_exports_destroy`] when
 * it is no longer needed.
 *
 * Returns a null pointer if `instance` is null.
 *
 * # Safety
 * `instance` must be either null or a valid, live [`StatorWasmInstance`]
 * pointer.
 */
char **stator_wasm_instance_exports(struct StatorWasmInstance *instance);

/**
 * Free the export-name array returned by [`stator_wasm_instance_exports`].
 *
 * Does nothing when `exports` is null.
 *
 * # Safety
 * `exports` must be either null or a valid pointer returned by
 * [`stator_wasm_instance_exports`] that has not been freed yet.
 */
void stator_wasm_exports_destroy(char **exports);

/**
 * Call an exported WebAssembly function by name.
 *
 * `args` is an array of `args_len` pointers to [`StatorValue`] handles used
 * as Wasm arguments.  Each null element is treated as `i32(0)`.  A null
 * `args` pointer with `args_len == 0` is valid and means no arguments.
 *
 * Returns a new [`StatorValue`] owned by the caller (free with
 * [`stator_value_destroy`]), or a null pointer if any required pointer
 * parameter is null, the named export does not exist, the call traps, or the
 * first result cannot be represented as a [`StatorValue`].  Void (zero-result)
 * functions return `undefined`.
 *
 * # Safety
 * - `instance` must be a non-null, valid pointer to a live
 *   [`StatorWasmInstance`].
 * - `isolate` must be a non-null, valid pointer to a live [`StatorIsolate`].
 * - `name` must be a valid, null-terminated C string.
 * - `args` must be valid for reads of `args_len` pointers; each non-null
 *   element must be a valid, live [`StatorValue`] pointer.
 */
struct StatorValue *stator_wasm_instance_call(struct StatorWasmInstance *instance,
                                              struct StatorIsolate *isolate,
                                              const char *name,
                                              const struct StatorValue *const *args,
                                              size_t args_len);

/**
 * Bind a CDP WebSocket server to `127.0.0.1:<port>`.
 *
 * Passing `port = 0` lets the OS choose a free port; use
 * [`stator_cdp_server_local_port`] to discover the actual port.
 *
 * Returns a non-null handle on success, or null on failure (e.g. port already
 * in use).  The handle must eventually be freed with
 * [`stator_cdp_server_destroy`].
 */
struct StatorCdpServer *stator_cdp_server_create(uint16_t port);

/**
 * Return the TCP port that `server` is bound to.
 *
 * # Safety
 * `server` must be a non-null pointer returned by [`stator_cdp_server_create`].
 */
uint16_t stator_cdp_server_local_port(const struct StatorCdpServer *server);

/**
 * Spawn a background OS thread that accepts and serves CDP connections in a
 * loop, transferring ownership of `server` to the new thread.
 *
 * After this call the `server` pointer is **consumed** and must **not** be
 * passed to [`stator_cdp_server_destroy`] or any other function.  The
 * background thread runs until the process exits.  Any per-connection errors
 * are silently ignored.
 *
 * Does nothing if `server` is null.
 *
 * # Safety
 * `server` must be null or a valid, uniquely-owned pointer returned by
 * [`stator_cdp_server_create`] that has not already been consumed.
 */
void stator_cdp_server_run_background(struct StatorCdpServer *server);

/**
 * Free a CDP server returned by [`stator_cdp_server_create`].
 *
 * Does nothing if `server` is null.
 *
 * # Safety
 * `server` must be null or a valid pointer returned by
 * [`stator_cdp_server_create`].  Must not be called more than once for the
 * same pointer.
 */
void stator_cdp_server_destroy(struct StatorCdpServer *server);

/**
 * Create a new debug session for `script`.
 *
 * Compiles `script` and prepares an interpreter frame; does **not** start
 * execution.  Call [`stator_debug_session_set_breakpoint_at_line`] to
 * install breakpoints, then [`stator_debug_session_run`] to begin execution.
 *
 * Returns null if `script` or `ctx` is null, if `script` has a compile
 * error, or if allocation fails.  The returned handle must eventually be
 * freed with [`stator_debug_session_destroy`].
 *
 * # Safety
 * - `script` must be a non-null pointer returned by [`stator_script_compile`]
 *   with no compile error.
 * - `ctx` must be a non-null pointer to a live [`StatorContext`].
 */
struct StatorDebugSession *stator_debug_session_create(const struct StatorScript *script,
                                                       struct StatorContext *ctx);

/**
 * Install a breakpoint at the given 1-based source line in `session`.
 *
 * Returns `true` if the breakpoint was successfully mapped to a bytecode
 * offset, `false` otherwise (e.g. the line has no executable code).
 *
 * # Safety
 * `session` must be a non-null pointer returned by
 * [`stator_debug_session_create`].
 */
bool stator_debug_session_set_breakpoint_at_line(struct StatorDebugSession *session, uint32_t line);

/**
 * Run (or continue) the session until a breakpoint is hit or execution
 * completes.
 *
 * Returns `true` if execution paused at a breakpoint (the session is now in
 * a paused state and the caller may inspect variables).  Returns `false` when
 * execution finished normally or with an uncaught exception; the final result
 * is available via [`stator_debug_session_result`].
 *
 * # Safety
 * `session` must be a non-null pointer returned by
 * [`stator_debug_session_create`].
 */
bool stator_debug_session_run(struct StatorDebugSession *session);

/**
 * Returns `true` if the session is currently paused at a breakpoint.
 *
 * # Safety
 * `session` must be a non-null pointer returned by
 * [`stator_debug_session_create`].
 */
bool stator_debug_session_is_paused(const struct StatorDebugSession *session);

/**
 * Return the 1-based source line at which execution is currently paused, or
 * 0 if the session is not paused.
 *
 * # Safety
 * `session` must be a non-null pointer returned by
 * [`stator_debug_session_create`].
 */
uint32_t stator_debug_session_pause_line(const struct StatorDebugSession *session);

/**
 * Write the string representation of the global variable `name` into `buf`
 * (up to `buf_len − 1` bytes, always NUL-terminated).
 *
 * Returns the number of bytes written (excluding the NUL), or `-1` if the
 * variable does not exist or the session / buffer pointer is null.
 *
 * # Safety
 * - `session` must be a non-null pointer returned by
 *   [`stator_debug_session_create`].
 * - `name` must be a valid, null-terminated C string.
 * - `buf` must be valid for writes of at least `buf_len` bytes.
 */
int32_t stator_debug_session_get_global_string(const struct StatorDebugSession *session,
                                               const char *name,
                                               char *buf,
                                               size_t buf_len);

/**
 * Resume a paused session with a "continue" action (run until the next
 * breakpoint or completion).
 *
 * Equivalent to calling [`stator_debug_session_run`] after applying a
 * `Continue` action.  Returns `true` if execution pauses again, `false` if
 * it completes.
 *
 * Does nothing and returns `false` if the session is not paused or `session`
 * is null.
 *
 * # Safety
 * `session` must be a non-null pointer returned by
 * [`stator_debug_session_create`].
 */
bool stator_debug_session_resume(struct StatorDebugSession *session);

/**
 * Return a new [`StatorValue`] containing the final result of a completed
 * debug session, or null if the session has not yet completed.
 *
 * The returned value must be freed with [`stator_value_destroy`].
 *
 * # Safety
 * `session` must be a non-null pointer returned by
 * [`stator_debug_session_create`].
 */
struct StatorValue *stator_debug_session_result(const struct StatorDebugSession *session);

/**
 * Free a debug session returned by [`stator_debug_session_create`].
 *
 * Does nothing if `session` is null.
 *
 * # Safety
 * `session` must be null or a valid pointer returned by
 * [`stator_debug_session_create`].  Must not be called more than once for
 * the same pointer.
 */
void stator_debug_session_destroy(struct StatorDebugSession *session);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* STATOR_H */
