#ifndef STATOR_H
#define STATOR_H

/* THIS FILE WAS GENERATED BY cbindgen — DO NOT EDIT MANUALLY.
 * Re-run `cargo build -p stator_ffi` to regenerate.
 */

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * An opaque context handle.
 *
 * A context represents an execution environment associated with an
 * [`StatorIsolate`].  The caller must pass the returned pointer to
 * [`stator_context_destroy`] when the context is no longer needed.
 */
typedef struct StatorContext StatorContext;

/**
 * An opaque isolate handle.
 *
 * An isolate is an independent instance of the Stator engine with its own
 * heap and root set.  Isolates are not thread-safe by default; access from
 * multiple threads requires external synchronisation.
 */
typedef struct StatorIsolate StatorIsolate;

/**
 * An opaque handle to a JavaScript object.
 *
 * Created by [`stator_object_new`] and destroyed by [`stator_object_destroy`].
 * Named properties can be set and retrieved via [`stator_object_set`] and
 * [`stator_object_get`].
 */
typedef struct StatorObject StatorObject;

/**
 * The outcome of a `stator_script_compile` call.
 *
 * Created by [`stator_script_compile`] and released by [`stator_script_free`].
 */
typedef struct StatorScript StatorScript;

/**
 * An opaque handle to a JavaScript value (number or string).
 *
 * Created by [`stator_value_new_number`] or [`stator_value_new_string`] and
 * destroyed by [`stator_value_destroy`].  The live-object counter on the
 * parent isolate is incremented on creation and decremented on destruction.
 */
typedef struct StatorValue StatorValue;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Create a new isolate.
 *
 * The returned pointer must eventually be passed to [`stator_isolate_destroy`]
 * to free all associated resources.  Returns a null pointer on allocation
 * failure (extremely unlikely in practice).
 */
struct StatorIsolate *stator_isolate_create(void);

/**
 * Destroy an isolate previously created with [`stator_isolate_create`].
 *
 * After this call the pointer is invalid and must not be used.
 *
 * # Safety
 * - `isolate` must be a non-null pointer returned by `stator_isolate_create`.
 * - `isolate` must not be used again after this call.
 * - This function must not be called more than once for the same pointer.
 */
void stator_isolate_destroy(struct StatorIsolate *isolate);

/**
 * Trigger a minor (young-generation) garbage collection on the isolate's heap.
 *
 * # Safety
 * `isolate` must be a non-null, valid pointer to a live `StatorIsolate`.
 */
void stator_isolate_gc(struct StatorIsolate *isolate);

/**
 * Create a new context associated with `isolate`.
 *
 * Returns a null pointer if `isolate` is null.  The caller must eventually
 * pass the returned pointer to [`stator_context_destroy`].
 *
 * # Safety
 * `isolate` must be a non-null, valid pointer to a live [`StatorIsolate`].
 */
struct StatorContext *stator_context_new(struct StatorIsolate *isolate);

/**
 * Destroy a context previously created with [`stator_context_new`].
 *
 * # Safety
 * `ctx` must be a non-null pointer returned by `stator_context_new` and must
 * not be used again after this call.
 */
void stator_context_destroy(struct StatorContext *ctx);

/**
 * Create a new number value.
 *
 * Returns a null pointer if `isolate` is null.
 *
 * # Safety
 * `isolate` must be a non-null, valid pointer to a live [`StatorIsolate`].
 */
struct StatorValue *stator_value_new_number(struct StatorIsolate *isolate, double val);

/**
 * Create a new string value from a buffer of `len` bytes.
 *
 * `data` need not be null-terminated; `len` bytes are copied.  Any embedded
 * null bytes are replaced by truncating at the first null.  Returns a null
 * pointer if `isolate` or `data` is null.
 *
 * # Safety
 * - `isolate` must be a non-null, valid pointer to a live [`StatorIsolate`].
 * - `data` must be valid for reads of `len` bytes.
 */
struct StatorValue *stator_value_new_string(struct StatorIsolate *isolate,
                                            const char *data,
                                            size_t len);

/**
 * Destroy a value and decrement the isolate's live-object counter.
 *
 * # Safety
 * `val` must be a non-null pointer returned by `stator_value_new_number` or
 * `stator_value_new_string` and must not be used again after this call.
 */
void stator_value_destroy(struct StatorValue *val);

/**
 * Return a static C string describing the type of `val`: `"number"` or
 * `"string"`.
 *
 * Returns `"undefined"` when `val` is null.  The returned pointer is valid
 * for the lifetime of the process.
 *
 * # Safety
 * `val` must be either null or a valid, live [`StatorValue`] pointer.
 */
const char *stator_value_type(const struct StatorValue *val);

/**
 * Return the numeric value stored in `val`, or `NaN` if `val` is null or not
 * a number.
 *
 * # Safety
 * `val` must be either null or a valid, live [`StatorValue`] pointer.
 */
double stator_value_as_number(const struct StatorValue *val);

/**
 * Return a null-terminated C string for the string stored in `val`.
 *
 * Returns a pointer to an empty string (`""`) when `val` is null or not a
 * string.  The pointer is valid only as long as `val` is alive.
 *
 * # Safety
 * `val` must be either null or a valid, live [`StatorValue`] pointer.
 */
const char *stator_value_as_string(const struct StatorValue *val);

/**
 * Create a new, empty JavaScript object.
 *
 * Returns a null pointer if `isolate` is null.
 *
 * # Safety
 * `isolate` must be a non-null, valid pointer to a live [`StatorIsolate`].
 */
struct StatorObject *stator_object_new(struct StatorIsolate *isolate);

/**
 * Destroy an object and decrement the isolate's live-object counter.
 *
 * # Safety
 * `obj` must be a non-null pointer returned by `stator_object_new` and must
 * not be used again after this call.
 */
void stator_object_destroy(struct StatorObject *obj);

/**
 * Set (or overwrite) the named property `key` on `obj` to `val`.
 *
 * The value is copied by value into the object; the caller retains ownership
 * of `val` and must destroy it independently.  Does nothing if any argument
 * is null.
 *
 * # Safety
 * - `obj` must be a valid, live [`StatorObject`] pointer.
 * - `key` must be a valid, null-terminated C string.
 * - `val` must be a valid, live [`StatorValue`] pointer.
 */
void stator_object_set(struct StatorObject *obj, const char *key, const struct StatorValue *val);

/**
 * Get the named property `key` from `obj` as a new [`StatorValue`].
 *
 * Returns a null pointer if `obj` or `key` is null, or if the property does
 * not exist.  The caller owns the returned pointer and must pass it to
 * [`stator_value_destroy`].
 *
 * # Safety
 * - `obj` must be a valid, live [`StatorObject`] pointer.
 * - `key` must be a valid, null-terminated C string.
 */
struct StatorValue *stator_object_get(const struct StatorObject *obj, const char *key);

/**
 * Trigger a minor (young-generation) GC on the isolate heap.
 *
 * This is the preferred spelling for embedders using the Phase 1 object
 * model; it is equivalent to [`stator_isolate_gc`].
 *
 * # Safety
 * `isolate` must be a non-null, valid pointer to a live [`StatorIsolate`].
 */
void stator_gc_collect(struct StatorIsolate *isolate);

/**
 * Return the number of live embedder-owned handles (values + objects) that
 * have been created on `isolate` but not yet destroyed.
 *
 * After a GC cycle this count reflects how many objects would survive because
 * they are still reachable through live handles.
 *
 * Returns 0 when `isolate` is null.
 *
 * # Safety
 * `isolate` must be either null or a valid, live [`StatorIsolate`] pointer.
 */
size_t stator_live_object_count(const struct StatorIsolate *isolate);

/**
 * Return the number of bytes currently allocated in the young-generation
 * from-space.  This is 0 immediately after a GC cycle.
 *
 * Returns 0 when `isolate` is null.
 *
 * # Safety
 * `isolate` must be either null or a valid, live [`StatorIsolate`] pointer.
 */
size_t stator_heap_used(const struct StatorIsolate *isolate);

/**
 * Return the total capacity (in bytes) of the young-generation semi-space,
 * counting both the from-space and to-space halves.
 *
 * Returns 0 when `isolate` is null.
 *
 * # Safety
 * `isolate` must be either null or a valid, live [`StatorIsolate`] pointer.
 */
size_t stator_heap_capacity(const struct StatorIsolate *isolate);

/**
 * Compile `source` (a UTF-8 string of `source_len` bytes) into bytecode.
 *
 * Returns a non-null [`StatorScript`] pointer in all cases (even on error).
 * Call [`stator_script_get_error`] to check whether compilation succeeded.
 * The caller must eventually pass the returned pointer to
 * [`stator_script_free`].
 *
 * Returns a null pointer only on an internal allocation failure (extremely
 * unlikely in practice).
 *
 * # Safety
 * - `ctx` must be either null or a valid, live [`StatorContext`] pointer.
 * - `source` must be valid for reads of `source_len` bytes of valid UTF-8.
 */
struct StatorScript *stator_script_compile(struct StatorContext *_ctx,
                                           const char *source,
                                           size_t source_len);

/**
 * Return a null-terminated error message if `script` compiled with an error.
 *
 * Returns a null pointer when `script` compiled successfully.  The returned
 * pointer is valid as long as `script` is alive (i.e. until
 * [`stator_script_free`] is called).
 *
 * # Safety
 * `script` must be a non-null pointer returned by [`stator_script_compile`].
 */
const char *stator_script_get_error(const struct StatorScript *script);

/**
 * Print the decoded bytecode listing for `script` to standard output.
 *
 * Each instruction is printed on a new line in the form:
 * `  <OpcodeName> [<operand>, …]`
 *
 * Does nothing if `script` is null or compiled with an error.
 *
 * # Safety
 * `script` must be either null or a valid, live [`StatorScript`] pointer.
 */
void stator_bytecode_dump(const struct StatorScript *script);

/**
 * Return the number of bytecode instructions in a successfully compiled script.
 *
 * Returns 0 if `script` is null, compiled with an error, or the bytecode
 * stream cannot be decoded.
 *
 * # Safety
 * `script` must be either null or a valid, live [`StatorScript`] pointer.
 */
size_t stator_script_bytecode_count(const struct StatorScript *script);

/**
 * Free a [`StatorScript`] previously returned by [`stator_script_compile`].
 *
 * # Safety
 * `script` must be a non-null pointer returned by [`stator_script_compile`]
 * and must not be used again after this call.
 */
void stator_script_free(struct StatorScript *script);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* STATOR_H */
