/**
 * stator.h — Public C API for the Stator JavaScript engine.
 *
 * This header mirrors the symbols exported by `crates/stator_js_ffi`.  Link
 * against `libstator_js_ffi.a` (static) or `libstator_js_ffi.so` / `stator_js_ffi.dll`
 * (dynamic) to use this API.
 *
 * Ownership model
 * ---------------
 * All opaque handle types are heap-allocated by Stator and returned as raw
 * pointers.  The caller is responsible for passing them to the corresponding
 * `_destroy` / `_free` function when they are no longer needed.  Double-freeing
 * or using a handle after destruction is undefined behaviour.
 */

#ifndef STATOR_H
#define STATOR_H

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

/* -------------------------------------------------------------------------
 * Opaque types
 * ------------------------------------------------------------------------- */

/** An isolated JavaScript engine instance with its own heap and root set. */
typedef struct StatorIsolate StatorIsolate;

/** An execution context associated with an isolate. */
typedef struct StatorContext StatorContext;

/** A handle to a JavaScript value (number or string). */
typedef struct StatorValue StatorValue;

/** A handle to a JavaScript object with named properties. */
typedef struct StatorObject StatorObject;

/**
 * An opaque handle to a compiled JavaScript script.
 *
 * Returned by stator_script_compile().  Call stator_script_get_error() to
 * determine whether compilation succeeded, stator_bytecode_dump() to print
 * the generated bytecodes, and stator_script_free() when finished.
 */
typedef struct StatorScript StatorScript;

/**
 * An opaque handle to an embedder-provided platform implementation.
 *
 * Created by stator_platform_new() from a StatorPlatformVTable.
 * Must be destroyed with stator_platform_destroy() when no longer needed.
 */
typedef struct StatorPlatform StatorPlatform;

/**
 * An opaque handle scope that manages the lifetime of StatorValue handles.
 *
 * All StatorValue handles created (via stator_value_new_number() or
 * stator_value_new_string()) while a handle scope is the innermost open scope
 * on an isolate are automatically registered with that scope and will be freed
 * when stator_handle_scope_close() is called.
 *
 * The embedder must NOT call stator_value_destroy() on scope-owned handles.
 *
 * Created by stator_handle_scope_new().
 * Closed (and all owned values freed) by stator_handle_scope_close().
 */
typedef struct StatorHandleScope StatorHandleScope;

/**
 * An opaque escapable handle scope.
 *
 * Like StatorHandleScope, but allows a single value to be promoted ("escaped")
 * into the enclosing scope via stator_escapable_handle_scope_escape().
 *
 * Created by stator_escapable_handle_scope_new().
 * Closed by stator_escapable_handle_scope_close().
 */
typedef struct StatorEscapableHandleScope StatorEscapableHandleScope;

/* -------------------------------------------------------------------------
 * Platform vtable
 * ------------------------------------------------------------------------- */

/**
 * C-compatible vtable that embedders fill in to customise engine behaviour.
 *
 * All function pointer fields are optional (may be NULL).  When a field is
 * NULL the engine falls back to a default (no-op or zero return value).
 *
 * The function pointers must remain valid for the entire lifetime of the
 * owning StatorPlatform handle.
 */
typedef struct StatorPlatformVTable {
    /**
     * Return the number of worker threads available for background work.
     *
     * May be NULL; the engine defaults to 0 when unset.
     */
    uint32_t (*number_of_worker_threads)(void);

    /**
     * Schedule `task` for execution on a platform-managed thread.
     *
     * The platform takes ownership of `task`.  May be NULL (tasks are
     * silently dropped when unset).
     */
    void (*post_task)(void *task);

    /**
     * Return a monotonically increasing time in seconds.
     *
     * May be NULL; the engine returns 0.0 when unset.
     */
    double (*monotonically_increasing_time)(void);

    /**
     * Return the current wall-clock time in milliseconds since the Unix epoch.
     *
     * May be NULL; the engine returns 0.0 when unset.
     */
    double (*current_clock_time_millis)(void);
} StatorPlatformVTable;

/* -------------------------------------------------------------------------
 * Isolate lifecycle
 * ------------------------------------------------------------------------- */

/**
 * Create a new Stator isolate.
 *
 * Returns a pointer to a freshly initialised isolate.  The caller owns the
 * returned pointer and must eventually pass it to stator_isolate_destroy().
 *
 * Returns NULL on allocation failure (extremely rare in practice).
 */
StatorIsolate *stator_isolate_create(void);

/**
 * Create a new Stator isolate (V8-compatible spelling).
 *
 * Equivalent to stator_isolate_create().  The caller owns the returned pointer
 * and must eventually pass it to stator_isolate_dispose().
 *
 * Returns NULL on allocation failure (extremely rare in practice).
 */
StatorIsolate *stator_isolate_new(void);

/**
 * Destroy an isolate and release all associated resources.
 *
 * @param isolate  A non-NULL pointer previously returned by
 *                 stator_isolate_create().  Must not be used after this call.
 */
void stator_isolate_destroy(StatorIsolate *isolate);

/**
 * Dispose an isolate and release all associated resources
 * (V8-compatible spelling).
 *
 * Equivalent to stator_isolate_destroy().
 *
 * @param isolate  A non-NULL pointer previously returned by
 *                 stator_isolate_new().  Must not be used after this call.
 */
void stator_isolate_dispose(StatorIsolate *isolate);

/**
 * Mark the isolate as entered on the current thread.
 *
 * Each call to stator_isolate_enter() must be matched by a call to
 * stator_isolate_exit().  Does nothing when isolate is NULL.
 *
 * @param isolate  A valid, non-NULL isolate pointer.
 */
void stator_isolate_enter(StatorIsolate *isolate);

/**
 * Unmark the isolate as entered on the current thread.
 *
 * Must be called once for every preceding stator_isolate_enter() call.
 * Does nothing when isolate is NULL.
 *
 * @param isolate  A valid, non-NULL isolate pointer.
 */
void stator_isolate_exit(StatorIsolate *isolate);

/**
 * Store an opaque embedder-defined pointer at the given slot index.
 *
 * Slots are zero-indexed and grow on demand.  Storing NULL clears a slot.
 * Does nothing when isolate is NULL.
 *
 * @param isolate  A valid, non-NULL isolate pointer.
 * @param slot     Zero-based slot index.
 * @param data     The pointer to store (may be NULL).
 */
void stator_isolate_set_data(StatorIsolate *isolate, uint32_t slot, void *data);

/**
 * Retrieve the embedder-defined pointer stored at the given slot index.
 *
 * Returns NULL when isolate is NULL or the slot has not been set.
 *
 * @param isolate  A valid isolate pointer, or NULL.
 * @param slot     Zero-based slot index.
 * @return         The stored pointer, or NULL.
 */
void *stator_isolate_get_data(const StatorIsolate *isolate, uint32_t slot);

/**
 * Record exception as the pending exception on the isolate.
 *
 * The caller retains ownership of exception; the isolate holds a raw pointer
 * only.  Does nothing when isolate is NULL.
 *
 * @param isolate    A valid, non-NULL isolate pointer.
 * @param exception  A valid StatorValue pointer to record as pending (may be
 *                   NULL to clear).
 */
void stator_isolate_throw_exception(StatorIsolate *isolate, StatorValue *exception);

/**
 * Return the context most recently made current on isolate.
 *
 * A context is made current when it is created via stator_context_new() and
 * cleared when it is destroyed via stator_context_destroy().
 *
 * Returns NULL when isolate is NULL or no context is currently active.
 *
 * @param isolate  A valid isolate pointer, or NULL.
 * @return         The current StatorContext*, or NULL.
 */
StatorContext *stator_isolate_get_current_context(const StatorIsolate *isolate);

/* -------------------------------------------------------------------------
 * Heap / GC
 * ------------------------------------------------------------------------- */

/**
 * Trigger a minor (young-generation) garbage collection on the isolate heap.
 *
 * Safe to call at any point when no JavaScript code is currently executing
 * on the isolate.
 *
 * @param isolate  A valid, non-NULL isolate pointer.
 */
void stator_isolate_gc(StatorIsolate *isolate);

/**
 * Trigger a minor (young-generation) GC on the isolate heap.
 *
 * Preferred spelling for embedders using the Phase 1 object model.
 * Equivalent to stator_isolate_gc().
 *
 * @param isolate  A valid, non-NULL isolate pointer.
 */
void stator_gc_collect(StatorIsolate *isolate);

/**
 * Compilation tier statistics for an isolate.
 *
 * Filled in by stator_isolate_get_stats().  All counts are thread-local
 * totals accumulated since the process started.
 *
 * On platforms where the baseline JIT is not available (non-x86-64 or
 * non-Unix), all fields will always be zero.
 */
typedef struct StatorCompilationStats {
    /** Number of JavaScript functions compiled to baseline JIT. */
    uint32_t jit_functions_compiled;
    /** Total bytes of machine code produced by the baseline JIT compiler. */
    size_t   jit_code_bytes;
} StatorCompilationStats;

/**
 * Fill *stats with the current compilation tier statistics.
 *
 * Reports the cumulative number of baseline-JIT-compiled functions and the
 * total machine-code bytes produced on this thread since the process started.
 * On platforms where the JIT is unavailable all counts will be zero.
 *
 * Does nothing when stats is NULL.
 *
 * @param isolate  A valid isolate pointer (may be NULL; the parameter exists
 *                 for API consistency — stats are thread-local).
 * @param stats    A non-NULL pointer to a StatorCompilationStats to fill.
 */
void stator_isolate_get_stats(const StatorIsolate    *isolate,
                              StatorCompilationStats *stats);

/**
 * Return the number of live embedder-owned value/object handles on the
 * isolate.  After a GC cycle this reflects how many objects survive because
 * they are still held by live handles.
 *
 * @param isolate  A valid isolate pointer, or NULL (returns 0).
 */
size_t stator_live_object_count(const StatorIsolate *isolate);

/**
 * Return bytes currently allocated in the young-generation from-space.
 * This is 0 immediately after a GC cycle.
 *
 * @param isolate  A valid isolate pointer, or NULL (returns 0).
 */
size_t stator_heap_used(const StatorIsolate *isolate);

/**
 * Return the total capacity (both halves) of the young-generation semi-space
 * in bytes.
 *
 * @param isolate  A valid isolate pointer, or NULL (returns 0).
 */
size_t stator_heap_capacity(const StatorIsolate *isolate);

/* -------------------------------------------------------------------------
 * Context lifecycle
 * ------------------------------------------------------------------------- */

/**
 * Create a new execution context associated with `isolate`.
 *
 * Returns NULL if `isolate` is NULL.  The caller must eventually pass the
 * returned pointer to stator_context_destroy().
 *
 * @param isolate  A valid, non-NULL isolate pointer.
 */
StatorContext *stator_context_new(StatorIsolate *isolate);

/**
 * Destroy a context previously created with stator_context_new().
 *
 * @param ctx  A non-NULL pointer returned by stator_context_new().
 */
void stator_context_destroy(StatorContext *ctx);

/**
 * Mark `ctx` as entered on the current thread.
 *
 * Each call to stator_context_enter() must be matched by a call to
 * stator_context_exit().  Entering a context makes it the current context
 * on its associated isolate.  Does nothing when ctx is NULL.
 *
 * @param ctx  A valid context pointer, or NULL.
 */
void stator_context_enter(StatorContext *ctx);

/**
 * Unmark `ctx` as entered on the current thread.
 *
 * Must be called once for every preceding stator_context_enter() call.
 * When the enter count reaches zero the context is no longer current on its
 * associated isolate.  Does nothing when ctx is NULL.
 *
 * @param ctx  A valid context pointer, or NULL.
 */
void stator_context_exit(StatorContext *ctx);

/**
 * Return a non-owning pointer to the global object of `ctx`.
 *
 * The returned pointer is valid for as long as `ctx` is alive.  The caller
 * must NOT pass the returned pointer to stator_object_destroy(); the global
 * object is owned by the context.
 *
 * Returns NULL when ctx is NULL.
 *
 * @param ctx  A valid context pointer, or NULL.
 * @return     A pointer to the context's global StatorObject, or NULL.
 */
StatorObject *stator_context_global(StatorContext *ctx);

/* -------------------------------------------------------------------------
 * Value lifecycle
 * ------------------------------------------------------------------------- */

/**
 * Create a new number value.
 *
 * @param isolate  A valid, non-NULL isolate pointer.
 * @param val      The double-precision floating-point number to wrap.
 * @return         A new StatorValue*, or NULL on failure.
 */
StatorValue *stator_value_new_number(StatorIsolate *isolate, double val);

/**
 * Create a new string value from a buffer of `len` bytes.
 *
 * The buffer need not be null-terminated; `len` bytes are copied.
 *
 * @param isolate  A valid, non-NULL isolate pointer.
 * @param data     Pointer to the first byte of the string data.
 * @param len      Number of bytes to copy.
 * @return         A new StatorValue*, or NULL on failure.
 */
StatorValue *stator_value_new_string(StatorIsolate *isolate, const char *data, size_t len);

/**
 * Destroy a value and decrement the isolate's live-object counter.
 *
 * @param val  A non-NULL pointer returned by stator_value_new_number(),
 *             stator_value_new_string(), or stator_object_get().
 */
void stator_value_destroy(StatorValue *val);

/**
 * Return a static C string describing the type of `val`: "number" or
 * "string".  Returns "undefined" when `val` is NULL.
 *
 * @param val  A valid StatorValue pointer, or NULL.
 */
const char *stator_value_type(const StatorValue *val);

/**
 * Return the numeric value stored in `val`, or NaN if `val` is NULL or not
 * a number.
 *
 * @param val  A valid StatorValue pointer, or NULL.
 */
double stator_value_as_number(const StatorValue *val);

/**
 * Return a null-terminated C string for the string stored in `val`.
 *
 * Returns a pointer to an empty string when `val` is NULL or not a string.
 * The pointer is valid only as long as `val` is alive.
 *
 * @param val  A valid StatorValue pointer, or NULL.
 */
const char *stator_value_as_string(const StatorValue *val);

/* -------------------------------------------------------------------------
 * Object lifecycle
 * ------------------------------------------------------------------------- */

/**
 * Create a new, empty JavaScript object.
 *
 * @param isolate  A valid, non-NULL isolate pointer.
 * @return         A new StatorObject*, or NULL on failure.
 */
StatorObject *stator_object_new(StatorIsolate *isolate);

/**
 * Destroy an object and decrement the isolate's live-object counter.
 *
 * @param obj  A non-NULL pointer returned by stator_object_new().
 */
void stator_object_destroy(StatorObject *obj);

/**
 * Set (or overwrite) the named property `key` on `obj` to `val`.
 *
 * The value is copied into the object; the caller retains ownership of `val`.
 *
 * @param obj  A valid, non-NULL StatorObject pointer.
 * @param key  A null-terminated property name string.
 * @param val  A valid, non-NULL StatorValue pointer.
 */
void stator_object_set(StatorObject *obj, const char *key, const StatorValue *val);

/**
 * Get the named property `key` from `obj` as a new StatorValue.
 *
 * Returns NULL if `obj` or `key` is NULL or the property does not exist.
 * The caller owns the returned pointer and must pass it to
 * stator_value_destroy().
 *
 * @param obj  A valid, non-NULL StatorObject pointer.
 * @param key  A null-terminated property name string.
 */
StatorValue *stator_object_get(const StatorObject *obj, const char *key);

/* -------------------------------------------------------------------------
 * Script compilation (Phase 2: JavaScript parsing + bytecode generation)
 * ------------------------------------------------------------------------- */

/**
 * Compile `source` (a UTF-8 string of `source_len` bytes) to bytecode.
 *
 * The source string need not be null-terminated; exactly `source_len` bytes
 * are read.
 *
 * Always returns a non-NULL StatorScript* (even on parse errors).  The caller
 * must check stator_script_get_error() and must eventually pass the pointer to
 * stator_script_free().
 *
 * @param ctx         Execution context (may be NULL for standalone compilation).
 * @param source      Pointer to the first byte of the JavaScript source.
 * @param source_len  Length of the source string in bytes.
 * @return            A new StatorScript*, or NULL on an internal allocation
 *                    failure (extremely rare).
 */
StatorScript *stator_script_compile(StatorContext *ctx,
                                    const char    *source,
                                    size_t         source_len);

/**
 * Return a null-terminated error message if `script` compiled with an error.
 *
 * Returns NULL when `script` compiled successfully.  The returned pointer is
 * valid as long as `script` is alive (until stator_script_free() is called).
 *
 * @param script  A non-NULL pointer returned by stator_script_compile().
 */
const char *stator_script_get_error(const StatorScript *script);

/**
 * Print the decoded bytecode listing for `script` to standard output.
 *
 * Each instruction is printed on a new line in the form:
 *   "  OpcodeName [operand, ...]"
 *
 * Does nothing if `script` is NULL or compiled with an error.
 *
 * @param script  A valid StatorScript pointer, or NULL.
 */
void stator_bytecode_dump(const StatorScript *script);

/**
 * Return the number of bytecode instructions in a successfully compiled script.
 *
 * Returns 0 if `script` is NULL, compiled with an error, or the bytecode
 * stream cannot be decoded.
 *
 * @param script  A valid StatorScript pointer, or NULL.
 */
size_t stator_script_bytecode_count(const StatorScript *script);

/**
 * Free a StatorScript previously returned by stator_script_compile().
 *
 * @param script  A non-NULL pointer returned by stator_script_compile().
 *                Must not be used again after this call.
 */
void stator_script_free(StatorScript *script);

/* -------------------------------------------------------------------------
 * Script execution (Phase 3: JavaScript actually runs)
 * ------------------------------------------------------------------------- */

/**
 * C-callable native-function signature.
 *
 * Called by the engine when JavaScript code invokes a function registered via
 * stator_register_native_function().
 *
 * @param ctx   The active execution context.
 * @param args  Array of `argc` argument value pointers.  The pointers are
 *              valid only for the duration of this call; do **not** free them.
 * @param argc  Number of arguments in @p args.
 * @return      A new StatorValue* (caller must eventually free it) or NULL to
 *              return `undefined` to JavaScript.
 */
typedef StatorValue *(*StatorNativeCallback)(StatorContext *ctx,
                                             const StatorValue *const *args,
                                             int argc);

/**
 * Execute a compiled script in the given context and return the result.
 *
 * The script must have compiled without errors (stator_script_get_error()
 * must return NULL).  On success the return value is a new StatorValue* that
 * the caller must pass to stator_value_destroy() when done.  Returns NULL
 * when the script is NULL, compiled with an error, or an uncaught JavaScript
 * exception occurs during execution.
 *
 * @param script  A non-NULL, successfully compiled StatorScript*.
 * @param ctx     The execution context (may be NULL for a bare evaluation
 *                with an empty global environment).
 * @return        A new StatorValue* for the script's completion value, or
 *                NULL on failure / uncaught exception.
 */
StatorValue *stator_script_run(StatorScript *script, StatorContext *ctx);

/**
 * Convert the value `val` to a UTF-8 string and write it into `buf`.
 *
 * At most `buf_len` bytes (including the NUL terminator) are written.
 * Returns the number of bytes written **excluding** the NUL terminator, or
 * -1 on internal error.  Returns 0 and writes `""` when `val` is NULL.
 *
 * Pass `buf = NULL` and `buf_len = 0` to query the required buffer size
 * without writing any data.
 *
 * @param val      A valid StatorValue pointer, or NULL.
 * @param buf      Destination buffer, or NULL when querying the size.
 * @param buf_len  Size of @p buf in bytes (must be at least 1 to receive a
 *                 NUL-terminated string).
 * @return         Bytes written (excluding NUL), or -1 on error.
 */
int stator_value_to_string_utf8(const StatorValue *val, char *buf, size_t buf_len);

/**
 * Register a native C function as a global on the execution context.
 *
 * After registration, JavaScript code run via stator_script_run() may call
 * the function by @p name.  Use dot notation to install a method on a
 * namespace object: `"console.log"` installs `log` on the `console` global.
 *
 * Does nothing when @p ctx or @p name is NULL.
 *
 * @param ctx       A valid, non-NULL StatorContext*.
 * @param name      Null-terminated function name, e.g. `"print"` or
 *                  `"console.log"`.
 * @param callback  The C function to invoke.  Must remain callable for the
 *                  lifetime of @p ctx.
 */
void stator_register_native_function(StatorContext    *ctx,
                                     const char       *name,
                                     StatorNativeCallback callback);

/* -------------------------------------------------------------------------
 * Value construction (Phase 4 additions)
 * ------------------------------------------------------------------------- */

/**
 * Create a new plain-object value.
 *
 * Returns a new StatorValue* with type "object", or NULL if isolate is NULL.
 * The caller must eventually pass the returned pointer to
 * stator_value_destroy() (unless it is scope-owned).
 *
 * @param isolate  A valid, non-NULL isolate pointer.
 */
StatorValue *stator_value_new_object(StatorIsolate *isolate);

/* -------------------------------------------------------------------------
 * FunctionTemplate (Phase 4: v8-compatible native function registration)
 * ------------------------------------------------------------------------- */

/**
 * An opaque function-template handle.
 *
 * Associates a C callback with an isolate.  Use
 * stator_function_template_get_function() to obtain a callable StatorValue*,
 * then install it in a context's global environment via
 * stator_context_global_set().
 *
 * Created by stator_function_template_new().
 * Destroyed by stator_function_template_destroy().
 */
typedef struct StatorFunctionTemplate StatorFunctionTemplate;

/**
 * Call-site information passed to a function-template callback.
 *
 * The lifetime of a StatorFunctionCallbackInfo value is limited to the
 * duration of the native callback invocation.  The embedder must not store
 * the pointer beyond the callback's return.
 *
 * Use stator_function_callback_info_length() and
 * stator_function_callback_info_get() to access arguments, and
 * stator_function_callback_info_get_isolate() to retrieve the isolate.
 */
typedef struct StatorFunctionCallbackInfo StatorFunctionCallbackInfo;

/**
 * C-callable callback signature for function templates.
 *
 * Called by the engine when JavaScript code invokes a function created via
 * stator_function_template_get_function().
 *
 * @param info  Call-site information (arguments, isolate).  Valid only for
 *              the duration of this call.
 * @return      A new StatorValue* (caller must eventually free it) or NULL to
 *              return `undefined` to JavaScript.
 */
typedef StatorValue *(*StatorFunctionTemplateCallback)(
    const StatorFunctionCallbackInfo *info);

/**
 * Return the number of arguments passed to this call.
 *
 * Returns 0 when info is NULL.
 *
 * @param info  A valid StatorFunctionCallbackInfo pointer, or NULL.
 */
int stator_function_callback_info_length(const StatorFunctionCallbackInfo *info);

/**
 * Return a pointer to the argument at position index.
 *
 * The returned pointer is valid only for the duration of the callback
 * invocation.  Returns NULL if info is NULL or index is out of range.
 *
 * @param info   A valid StatorFunctionCallbackInfo pointer, or NULL.
 * @param index  Zero-based argument index.
 */
const StatorValue *stator_function_callback_info_get(
    const StatorFunctionCallbackInfo *info, int index);

/**
 * Return the isolate associated with this call.
 *
 * Returns NULL if info is NULL.
 *
 * @param info  A valid StatorFunctionCallbackInfo pointer, or NULL.
 */
StatorIsolate *stator_function_callback_info_get_isolate(
    const StatorFunctionCallbackInfo *info);

/**
 * Create a new function template associated with isolate.
 *
 * Returns NULL if isolate is NULL.  The caller must eventually pass the
 * returned pointer to stator_function_template_destroy().
 *
 * @param isolate   A valid, non-NULL isolate pointer.
 * @param callback  The C function to invoke when the template's function is
 *                  called from JavaScript.  Must remain valid for the
 *                  lifetime of the template.
 */
StatorFunctionTemplate *stator_function_template_new(
    StatorIsolate                  *isolate,
    StatorFunctionTemplateCallback  callback);

/**
 * Destroy a function template previously created with
 * stator_function_template_new().
 *
 * Does nothing if tmpl is NULL.
 *
 * @param tmpl  A pointer returned by stator_function_template_new(), or NULL.
 */
void stator_function_template_destroy(StatorFunctionTemplate *tmpl);

/**
 * Produce a callable StatorValue* representing the function described by tmpl.
 *
 * The returned value has type "function" and can be installed into a context's
 * global environment via stator_context_global_set().  Returns NULL if tmpl is
 * NULL.  The caller owns the returned pointer and must eventually pass it to
 * stator_value_destroy().
 *
 * @param tmpl  A valid StatorFunctionTemplate pointer, or NULL.
 * @param ctx   The context the function will be used in (may be NULL).
 */
StatorValue *stator_function_template_get_function(
    const StatorFunctionTemplate *tmpl,
    StatorContext                *ctx);

/**
 * Install a value into the context's global environment under name.
 *
 * After this call, JavaScript code running via stator_script_run() can
 * reference name as a global variable.  Use dot notation to install a value
 * on a namespace object: "document.getElementById" creates a `document`
 * global (if it does not already exist) and sets its `getElementById`
 * property.  Does nothing if ctx or name is NULL.  A null val installs
 * undefined.
 *
 * @param ctx   A valid, non-NULL StatorContext*.
 * @param name  Null-terminated variable name; dot notation supported.
 * @param val   A valid StatorValue pointer, or NULL to install undefined.
 */
void stator_context_global_set(StatorContext      *ctx,
                                const char         *name,
                                const StatorValue  *val);

/* -------------------------------------------------------------------------
 * Handle scope lifecycle
 * ------------------------------------------------------------------------- */

/**
 * Open a new handle scope on isolate.
 *
 * All StatorValue handles created (via stator_value_new_number() or
 * stator_value_new_string()) after this call, and before the matching
 * stator_handle_scope_close(), are owned by the returned scope and will be
 * freed automatically when the scope is closed.
 *
 * The embedder must NOT call stator_value_destroy() on scope-owned handles.
 *
 * Handle scopes nest: it is valid to open multiple scopes and they must be
 * closed in LIFO order.
 *
 * Returns NULL if isolate is NULL.  The caller must eventually pass the
 * returned pointer to stator_handle_scope_close().
 *
 * @param isolate  A valid, non-NULL isolate pointer.
 * @return         A new StatorHandleScope*, or NULL if isolate is NULL.
 */
StatorHandleScope *stator_handle_scope_new(StatorIsolate *isolate);

/**
 * Close a handle scope and destroy all values registered with it.
 *
 * After this call, all StatorValue pointers created while scope was active
 * are invalid.  The previous scope (if any) is restored as the active scope.
 *
 * Does nothing if scope is NULL.
 *
 * @param scope  A non-NULL pointer returned by stator_handle_scope_new().
 *               Must be the innermost open scope.  Must not be used after
 *               this call.
 */
void stator_handle_scope_close(StatorHandleScope *scope);

/**
 * Open a new escapable handle scope on isolate.
 *
 * Like stator_handle_scope_new(), but allows a single value to be promoted
 * into the enclosing scope via stator_escapable_handle_scope_escape().
 *
 * Returns NULL if isolate is NULL.  The caller must eventually pass the
 * returned pointer to stator_escapable_handle_scope_close().
 *
 * @param isolate  A valid, non-NULL isolate pointer.
 * @return         A new StatorEscapableHandleScope*, or NULL if isolate is
 *                 NULL.
 */
StatorEscapableHandleScope *stator_escapable_handle_scope_new(StatorIsolate *isolate);

/**
 * Escape val from scope, promoting it into the enclosing scope.
 *
 * Removes val from scope's tracked handles so it will not be destroyed when
 * the scope is closed.  If there is an enclosing scope, val is registered
 * there; otherwise the caller takes ownership and must eventually pass val to
 * stator_value_destroy().
 *
 * Returns val unchanged (for convenient chaining), or NULL if scope or val
 * is NULL.
 *
 * Each value may only be escaped once.
 *
 * @param scope  A valid StatorEscapableHandleScope pointer, or NULL.
 * @param val    A non-NULL StatorValue pointer registered with scope.
 * @return       val, or NULL if scope or val is NULL.
 */
StatorValue *stator_escapable_handle_scope_escape(StatorEscapableHandleScope *scope,
                                                  StatorValue               *val);

/**
 * Close an escapable handle scope and destroy all non-escaped values.
 *
 * Equivalent to stator_handle_scope_close() for the escapable variant.
 *
 * Does nothing if scope is NULL.
 *
 * @param scope  A non-NULL pointer returned by
 *               stator_escapable_handle_scope_new().  Must be the innermost
 *               open scope.  Must not be used after this call.
 */
void stator_escapable_handle_scope_close(StatorEscapableHandleScope *scope);

/* -------------------------------------------------------------------------
 * Platform (embedder-provided task scheduling and timing)
 * ------------------------------------------------------------------------- */

/**
 * Create a new platform handle from an embedder-supplied vtable.
 *
 * The vtable is copied by value; the caller does not need to keep the
 * StatorPlatformVTable alive after this call returns.
 *
 * Returns NULL if `vtable` is NULL.  The caller must eventually pass the
 * returned pointer to stator_platform_destroy().
 *
 * @param vtable  A valid, non-NULL pointer to a StatorPlatformVTable.
 * @return        A new StatorPlatform*, or NULL if `vtable` is NULL.
 */
StatorPlatform *stator_platform_new(const StatorPlatformVTable *vtable);

/**
 * Destroy a platform previously created with stator_platform_new().
 *
 * @param platform  A non-NULL pointer returned by stator_platform_new().
 *                  Must not be used again after this call.
 */
void stator_platform_destroy(StatorPlatform *platform);

/**
 * Return the number of worker threads reported by `platform`.
 *
 * Returns 0 when `platform` is NULL or the vtable entry was not set.
 *
 * @param platform  A valid StatorPlatform pointer, or NULL.
 */
uint32_t stator_platform_number_of_worker_threads(const StatorPlatform *platform);

/**
 * Schedule `task` for execution on `platform`.
 *
 * Does nothing when `platform` is NULL, `task` is NULL, or the vtable entry
 * was not set.
 *
 * @param platform  A valid StatorPlatform pointer, or NULL.
 * @param task      An opaque task pointer; ownership transfers to the platform.
 */
void stator_platform_post_task(const StatorPlatform *platform, void *task);

/**
 * Return the monotonically increasing time (seconds) from `platform`.
 *
 * Returns 0.0 when `platform` is NULL or the vtable entry was not set.
 *
 * @param platform  A valid StatorPlatform pointer, or NULL.
 */
double stator_platform_monotonically_increasing_time(const StatorPlatform *platform);

/**
 * Return the current clock time in milliseconds from `platform`.
 *
 * Returns 0.0 when `platform` is NULL or the vtable entry was not set.
 *
 * @param platform  A valid StatorPlatform pointer, or NULL.
 */
double stator_platform_current_clock_time_millis(const StatorPlatform *platform);

/* -------------------------------------------------------------------------
 * WebAssembly
 * ------------------------------------------------------------------------- */

/** Opaque handle to a compiled WebAssembly module. */
typedef struct StatorWasmModule   StatorWasmModule;

/** Opaque handle to a live WebAssembly module instance. */
typedef struct StatorWasmInstance StatorWasmInstance;

/**
 * Compile a WebAssembly binary (or WAT text) into a StatorWasmModule.
 *
 * Returns NULL if any pointer argument is NULL, len is zero, or if the
 * bytes are not valid WebAssembly.  The caller must free the returned
 * handle with stator_wasm_module_destroy().
 *
 * @param isolate  A valid, non-NULL isolate pointer.
 * @param bytes    Pointer to the raw .wasm bytes (or WAT text bytes).
 * @param len      Length of the bytes buffer in bytes.
 */
StatorWasmModule *stator_wasm_compile(StatorIsolate *isolate,
                                      const uint8_t *bytes,
                                      size_t         len);

/**
 * Free a StatorWasmModule returned by stator_wasm_compile().
 *
 * Does nothing if module is NULL.
 */
void stator_wasm_module_destroy(StatorWasmModule *module);

/**
 * Instantiate a StatorWasmModule into a live StatorWasmInstance.
 *
 * ctx and imports are reserved for future use and may be NULL.
 * Returns NULL if module is NULL or instantiation fails.  The caller
 * must free the returned handle with stator_wasm_instance_destroy().
 *
 * @param module   A valid, non-NULL StatorWasmModule pointer.
 * @param ctx      Reserved; pass NULL.
 * @param imports  Reserved; must be NULL.
 */
StatorWasmInstance *stator_wasm_instantiate(StatorWasmModule *module,
                                             StatorContext    *ctx,
                                             const void       *imports);

/**
 * Free a StatorWasmInstance returned by stator_wasm_instantiate().
 *
 * Does nothing if instance is NULL.
 */
void stator_wasm_instance_destroy(StatorWasmInstance *instance);

/**
 * Call an exported WebAssembly function by name.
 *
 * args is an array of args_len StatorValue pointers used as Wasm
 * arguments (NULL elements are treated as i32(0)).  A NULL args pointer
 * with args_len == 0 means no arguments.
 *
 * Returns a new StatorValue (free with stator_value_destroy()) holding
 * the first result, an undefined value for void functions, or NULL on
 * error.
 *
 * @param instance  A valid, non-NULL StatorWasmInstance pointer.
 * @param isolate   A valid, non-NULL StatorIsolate pointer.
 * @param name      Null-terminated name of the exported function.
 * @param args      Array of StatorValue* arguments, or NULL.
 * @param args_len  Number of elements in args.
 */
StatorValue *stator_wasm_instance_call(StatorWasmInstance    *instance,
                                        StatorIsolate         *isolate,
                                        const char            *name,
                                        const StatorValue *const *args,
                                        size_t                 args_len);

/**
 * Return a NULL-terminated array of export names from instance.
 *
 * Each element is a heap-allocated, null-terminated C string.  The
 * caller must free the array with stator_wasm_exports_destroy().
 * Returns NULL if instance is NULL.
 */
char **stator_wasm_instance_exports(StatorWasmInstance *instance);

/**
 * Free an export-name array returned by stator_wasm_instance_exports().
 *
 * Does nothing if exports is NULL.
 */
void stator_wasm_exports_destroy(char **exports);

/* -------------------------------------------------------------------------
 * CDP WebSocket server (Phase 9)
 * ------------------------------------------------------------------------- */

/**
 * An opaque handle to a Chrome DevTools Protocol (CDP) WebSocket server.
 *
 * Created by stator_cdp_server_create().  Once created, the server can be
 * used in one of two ways:
 *
 *   - Pass it to stator_cdp_server_run_background() to hand ownership to a
 *     background thread that will serve connections indefinitely.  The handle
 *     must NOT be used or destroyed after this call.
 *
 *   - Destroy it with stator_cdp_server_destroy() without ever starting it.
 */
typedef struct StatorCdpServer StatorCdpServer;

/**
 * Bind a CDP WebSocket server to 127.0.0.1:<port>.
 *
 * Passing port = 0 lets the OS choose a free port; call
 * stator_cdp_server_local_port() to discover the actual port.
 *
 * Returns a non-null handle on success, or NULL if the port is unavailable.
 * The returned handle is owned by the caller until it is passed to
 * stator_cdp_server_run_background() or stator_cdp_server_destroy().
 *
 * @param port  TCP port to listen on; 0 = OS-assigned.
 */
StatorCdpServer *stator_cdp_server_create(uint16_t port);

/**
 * Return the TCP port that server is currently bound to.
 *
 * Returns 0 if server is NULL or the port cannot be determined.
 *
 * @param server  A valid, non-NULL StatorCdpServer pointer.
 */
uint16_t stator_cdp_server_local_port(const StatorCdpServer *server);

/**
 * Spawn a background OS thread that accepts and serves CDP connections
 * in a loop, consuming (transferring ownership of) server.
 *
 * After this call server is invalid and must NOT be passed to
 * stator_cdp_server_destroy() or any other function.
 *
 * Does nothing if server is NULL.
 *
 * @param server  A valid, uniquely-owned StatorCdpServer pointer.
 */
void stator_cdp_server_run_background(StatorCdpServer *server);

/**
 * Free a StatorCdpServer returned by stator_cdp_server_create().
 *
 * Must NOT be called after stator_cdp_server_run_background() has consumed
 * the handle.  Does nothing if server is NULL.
 */
void stator_cdp_server_destroy(StatorCdpServer *server);

/* -------------------------------------------------------------------------
 * Debug session (Phase 9)
 * ------------------------------------------------------------------------- */

/**
 * An opaque handle to an interactive debugging session.
 *
 * A session owns both the compiled bytecode frame and an attached debugger,
 * allowing the host to set breakpoints, step through execution, and inspect
 * variable values.
 *
 * Lifecycle:
 *   1. Create with stator_debug_session_create().
 *   2. Install breakpoints with stator_debug_session_set_breakpoint_at_line().
 *   3. Call stator_debug_session_run() — returns true when paused, false when
 *      execution completes.
 *   4. When paused, read globals with stator_debug_session_get_global_string().
 *   5. Resume with stator_debug_session_resume() — returns true if paused again.
 *   6. After completion, retrieve the result with stator_debug_session_result().
 *   7. Free with stator_debug_session_destroy().
 */
typedef struct StatorDebugSession StatorDebugSession;

/**
 * Create a new debug session for script.
 *
 * Compiles script and prepares an interpreter frame; does NOT start
 * execution.  Returns NULL if script or ctx is NULL, if script has a compile
 * error, or on allocation failure.
 *
 * @param script  A non-NULL StatorScript pointer with no compile error.
 * @param ctx     A non-NULL, live StatorContext pointer.
 */
StatorDebugSession *stator_debug_session_create(const StatorScript *script,
                                                StatorContext      *ctx);

/**
 * Install a breakpoint at 1-based source line in session.
 *
 * Returns true if the line was mapped to a bytecode offset, false otherwise.
 *
 * @param session  A valid, non-NULL StatorDebugSession pointer.
 * @param line     1-based source line number.
 */
bool stator_debug_session_set_breakpoint_at_line(StatorDebugSession *session,
                                                 uint32_t            line);

/**
 * Run the session until a breakpoint is hit or execution completes.
 *
 * Returns true if execution paused (the caller may inspect variables and
 * then call stator_debug_session_resume()).  Returns false when execution
 * has completed; the result is available via stator_debug_session_result().
 *
 * @param session  A valid, non-NULL StatorDebugSession pointer.
 */
bool stator_debug_session_run(StatorDebugSession *session);

/**
 * Returns true if session is currently paused at a breakpoint.
 *
 * @param session  A valid, non-NULL StatorDebugSession pointer.
 */
bool stator_debug_session_is_paused(const StatorDebugSession *session);

/**
 * Return the 1-based source line at which execution is paused, or 0 if
 * the session is not paused or the line is unknown.
 *
 * @param session  A valid, non-NULL StatorDebugSession pointer.
 */
uint32_t stator_debug_session_pause_line(const StatorDebugSession *session);

/**
 * Write the string representation of global variable name into buf
 * (at most buf_len-1 bytes, always NUL-terminated).
 *
 * Returns the number of bytes written (excluding the NUL), or -1 if the
 * variable does not exist or any pointer is NULL / buf_len is 0.
 *
 * @param session   A valid, non-NULL StatorDebugSession pointer.
 * @param name      Null-terminated variable name.
 * @param buf       Output buffer; at least buf_len bytes.
 * @param buf_len   Size of buf in bytes (must be >= 1).
 */
int stator_debug_session_get_global_string(const StatorDebugSession *session,
                                           const char               *name,
                                           char                     *buf,
                                           size_t                    buf_len);

/**
 * Resume a paused session and run until the next pause or completion.
 *
 * Returns true if execution pauses again, false if it completes.
 * Does nothing and returns false if session is not paused or is NULL.
 *
 * @param session  A valid, non-NULL StatorDebugSession pointer.
 */
bool stator_debug_session_resume(StatorDebugSession *session);

/**
 * Return a new StatorValue containing the final result of a completed
 * debug session, or NULL if the session has not yet completed.
 *
 * The returned value must be freed with stator_value_destroy().
 *
 * @param session  A valid, non-NULL StatorDebugSession pointer.
 */
StatorValue *stator_debug_session_result(const StatorDebugSession *session);

/**
 * Free a StatorDebugSession returned by stator_debug_session_create().
 *
 * Does nothing if session is NULL.
 */
void stator_debug_session_destroy(StatorDebugSession *session);

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif /* STATOR_H */

