/**
 * stator.h — Public C API for the Stator JavaScript engine.
 *
 * This header mirrors the symbols exported by `crates/stator_ffi`.  Link
 * against `libstator_ffi.a` (static) or `libstator_ffi.so` / `stator_ffi.dll`
 * (dynamic) to use this API.
 *
 * Ownership model
 * ---------------
 * All opaque handle types are heap-allocated by Stator and returned as raw
 * pointers.  The caller is responsible for passing them to the corresponding
 * `_destroy` / `_free` function when they are no longer needed.  Double-freeing
 * or using a handle after destruction is undefined behaviour.
 */

#ifndef STATOR_H
#define STATOR_H

#include <stddef.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

/* -------------------------------------------------------------------------
 * Opaque types
 * ------------------------------------------------------------------------- */

/** An isolated JavaScript engine instance with its own heap and root set. */
typedef struct StatorIsolate StatorIsolate;

/** An execution context associated with an isolate. */
typedef struct StatorContext StatorContext;

/** A handle to a JavaScript value (number or string). */
typedef struct StatorValue StatorValue;

/** A handle to a JavaScript object with named properties. */
typedef struct StatorObject StatorObject;

/**
 * An opaque handle to a compiled JavaScript script.
 *
 * Returned by stator_script_compile().  Call stator_script_get_error() to
 * determine whether compilation succeeded, stator_bytecode_dump() to print
 * the generated bytecodes, and stator_script_free() when finished.
 */
typedef struct StatorScript StatorScript;

/**
 * An opaque handle to an embedder-provided platform implementation.
 *
 * Created by stator_platform_new() from a StatorPlatformVTable.
 * Must be destroyed with stator_platform_destroy() when no longer needed.
 */
typedef struct StatorPlatform StatorPlatform;

/**
 * An opaque handle scope that manages the lifetime of StatorValue handles.
 *
 * All StatorValue handles created (via stator_value_new_number() or
 * stator_value_new_string()) while a handle scope is the innermost open scope
 * on an isolate are automatically registered with that scope and will be freed
 * when stator_handle_scope_close() is called.
 *
 * The embedder must NOT call stator_value_destroy() on scope-owned handles.
 *
 * Created by stator_handle_scope_new().
 * Closed (and all owned values freed) by stator_handle_scope_close().
 */
typedef struct StatorHandleScope StatorHandleScope;

/**
 * An opaque escapable handle scope.
 *
 * Like StatorHandleScope, but allows a single value to be promoted ("escaped")
 * into the enclosing scope via stator_escapable_handle_scope_escape().
 *
 * Created by stator_escapable_handle_scope_new().
 * Closed by stator_escapable_handle_scope_close().
 */
typedef struct StatorEscapableHandleScope StatorEscapableHandleScope;

/* -------------------------------------------------------------------------
 * Platform vtable
 * ------------------------------------------------------------------------- */

/**
 * C-compatible vtable that embedders fill in to customise engine behaviour.
 *
 * All function pointer fields are optional (may be NULL).  When a field is
 * NULL the engine falls back to a default (no-op or zero return value).
 *
 * The function pointers must remain valid for the entire lifetime of the
 * owning StatorPlatform handle.
 */
typedef struct StatorPlatformVTable {
    /**
     * Return the number of worker threads available for background work.
     *
     * May be NULL; the engine defaults to 0 when unset.
     */
    uint32_t (*number_of_worker_threads)(void);

    /**
     * Schedule `task` for execution on a platform-managed thread.
     *
     * The platform takes ownership of `task`.  May be NULL (tasks are
     * silently dropped when unset).
     */
    void (*post_task)(void *task);

    /**
     * Return a monotonically increasing time in seconds.
     *
     * May be NULL; the engine returns 0.0 when unset.
     */
    double (*monotonically_increasing_time)(void);

    /**
     * Return the current wall-clock time in milliseconds since the Unix epoch.
     *
     * May be NULL; the engine returns 0.0 when unset.
     */
    double (*current_clock_time_millis)(void);
} StatorPlatformVTable;

/* -------------------------------------------------------------------------
 * Isolate lifecycle
 * ------------------------------------------------------------------------- */

/**
 * Create a new Stator isolate.
 *
 * Returns a pointer to a freshly initialised isolate.  The caller owns the
 * returned pointer and must eventually pass it to stator_isolate_destroy().
 *
 * Returns NULL on allocation failure (extremely rare in practice).
 */
StatorIsolate *stator_isolate_create(void);

/**
 * Create a new Stator isolate (V8-compatible spelling).
 *
 * Equivalent to stator_isolate_create().  The caller owns the returned pointer
 * and must eventually pass it to stator_isolate_dispose().
 *
 * Returns NULL on allocation failure (extremely rare in practice).
 */
StatorIsolate *stator_isolate_new(void);

/**
 * Destroy an isolate and release all associated resources.
 *
 * @param isolate  A non-NULL pointer previously returned by
 *                 stator_isolate_create().  Must not be used after this call.
 */
void stator_isolate_destroy(StatorIsolate *isolate);

/**
 * Dispose an isolate and release all associated resources
 * (V8-compatible spelling).
 *
 * Equivalent to stator_isolate_destroy().
 *
 * @param isolate  A non-NULL pointer previously returned by
 *                 stator_isolate_new().  Must not be used after this call.
 */
void stator_isolate_dispose(StatorIsolate *isolate);

/**
 * Mark the isolate as entered on the current thread.
 *
 * Each call to stator_isolate_enter() must be matched by a call to
 * stator_isolate_exit().  Does nothing when isolate is NULL.
 *
 * @param isolate  A valid, non-NULL isolate pointer.
 */
void stator_isolate_enter(StatorIsolate *isolate);

/**
 * Unmark the isolate as entered on the current thread.
 *
 * Must be called once for every preceding stator_isolate_enter() call.
 * Does nothing when isolate is NULL.
 *
 * @param isolate  A valid, non-NULL isolate pointer.
 */
void stator_isolate_exit(StatorIsolate *isolate);

/**
 * Store an opaque embedder-defined pointer at the given slot index.
 *
 * Slots are zero-indexed and grow on demand.  Storing NULL clears a slot.
 * Does nothing when isolate is NULL.
 *
 * @param isolate  A valid, non-NULL isolate pointer.
 * @param slot     Zero-based slot index.
 * @param data     The pointer to store (may be NULL).
 */
void stator_isolate_set_data(StatorIsolate *isolate, uint32_t slot, void *data);

/**
 * Retrieve the embedder-defined pointer stored at the given slot index.
 *
 * Returns NULL when isolate is NULL or the slot has not been set.
 *
 * @param isolate  A valid isolate pointer, or NULL.
 * @param slot     Zero-based slot index.
 * @return         The stored pointer, or NULL.
 */
void *stator_isolate_get_data(const StatorIsolate *isolate, uint32_t slot);

/**
 * Record exception as the pending exception on the isolate.
 *
 * The caller retains ownership of exception; the isolate holds a raw pointer
 * only.  Does nothing when isolate is NULL.
 *
 * @param isolate    A valid, non-NULL isolate pointer.
 * @param exception  A valid StatorValue pointer to record as pending (may be
 *                   NULL to clear).
 */
void stator_isolate_throw_exception(StatorIsolate *isolate, StatorValue *exception);

/**
 * Return the context most recently made current on isolate.
 *
 * A context is made current when it is created via stator_context_new() and
 * cleared when it is destroyed via stator_context_destroy().
 *
 * Returns NULL when isolate is NULL or no context is currently active.
 *
 * @param isolate  A valid isolate pointer, or NULL.
 * @return         The current StatorContext*, or NULL.
 */
StatorContext *stator_isolate_get_current_context(const StatorIsolate *isolate);

/* -------------------------------------------------------------------------
 * Heap / GC
 * ------------------------------------------------------------------------- */

/**
 * Trigger a minor (young-generation) garbage collection on the isolate heap.
 *
 * Safe to call at any point when no JavaScript code is currently executing
 * on the isolate.
 *
 * @param isolate  A valid, non-NULL isolate pointer.
 */
void stator_isolate_gc(StatorIsolate *isolate);

/**
 * Trigger a minor (young-generation) GC on the isolate heap.
 *
 * Preferred spelling for embedders using the Phase 1 object model.
 * Equivalent to stator_isolate_gc().
 *
 * @param isolate  A valid, non-NULL isolate pointer.
 */
void stator_gc_collect(StatorIsolate *isolate);

/**
 * Return the number of live embedder-owned value/object handles on the
 * isolate.  After a GC cycle this reflects how many objects survive because
 * they are still held by live handles.
 *
 * @param isolate  A valid isolate pointer, or NULL (returns 0).
 */
size_t stator_live_object_count(const StatorIsolate *isolate);

/**
 * Return bytes currently allocated in the young-generation from-space.
 * This is 0 immediately after a GC cycle.
 *
 * @param isolate  A valid isolate pointer, or NULL (returns 0).
 */
size_t stator_heap_used(const StatorIsolate *isolate);

/**
 * Return the total capacity (both halves) of the young-generation semi-space
 * in bytes.
 *
 * @param isolate  A valid isolate pointer, or NULL (returns 0).
 */
size_t stator_heap_capacity(const StatorIsolate *isolate);

/* -------------------------------------------------------------------------
 * Context lifecycle
 * ------------------------------------------------------------------------- */

/**
 * Create a new execution context associated with `isolate`.
 *
 * Returns NULL if `isolate` is NULL.  The caller must eventually pass the
 * returned pointer to stator_context_destroy().
 *
 * @param isolate  A valid, non-NULL isolate pointer.
 */
StatorContext *stator_context_new(StatorIsolate *isolate);

/**
 * Destroy a context previously created with stator_context_new().
 *
 * @param ctx  A non-NULL pointer returned by stator_context_new().
 */
void stator_context_destroy(StatorContext *ctx);

/**
 * Mark `ctx` as entered on the current thread.
 *
 * Each call to stator_context_enter() must be matched by a call to
 * stator_context_exit().  Entering a context makes it the current context
 * on its associated isolate.  Does nothing when ctx is NULL.
 *
 * @param ctx  A valid context pointer, or NULL.
 */
void stator_context_enter(StatorContext *ctx);

/**
 * Unmark `ctx` as entered on the current thread.
 *
 * Must be called once for every preceding stator_context_enter() call.
 * When the enter count reaches zero the context is no longer current on its
 * associated isolate.  Does nothing when ctx is NULL.
 *
 * @param ctx  A valid context pointer, or NULL.
 */
void stator_context_exit(StatorContext *ctx);

/**
 * Return a non-owning pointer to the global object of `ctx`.
 *
 * The returned pointer is valid for as long as `ctx` is alive.  The caller
 * must NOT pass the returned pointer to stator_object_destroy(); the global
 * object is owned by the context.
 *
 * Returns NULL when ctx is NULL.
 *
 * @param ctx  A valid context pointer, or NULL.
 * @return     A pointer to the context's global StatorObject, or NULL.
 */
StatorObject *stator_context_global(StatorContext *ctx);

/* -------------------------------------------------------------------------
 * Value lifecycle
 * ------------------------------------------------------------------------- */

/**
 * Create a new number value.
 *
 * @param isolate  A valid, non-NULL isolate pointer.
 * @param val      The double-precision floating-point number to wrap.
 * @return         A new StatorValue*, or NULL on failure.
 */
StatorValue *stator_value_new_number(StatorIsolate *isolate, double val);

/**
 * Create a new string value from a buffer of `len` bytes.
 *
 * The buffer need not be null-terminated; `len` bytes are copied.
 *
 * @param isolate  A valid, non-NULL isolate pointer.
 * @param data     Pointer to the first byte of the string data.
 * @param len      Number of bytes to copy.
 * @return         A new StatorValue*, or NULL on failure.
 */
StatorValue *stator_value_new_string(StatorIsolate *isolate, const char *data, size_t len);

/**
 * Destroy a value and decrement the isolate's live-object counter.
 *
 * @param val  A non-NULL pointer returned by stator_value_new_number(),
 *             stator_value_new_string(), or stator_object_get().
 */
void stator_value_destroy(StatorValue *val);

/**
 * Return a static C string describing the type of `val`: "number" or
 * "string".  Returns "undefined" when `val` is NULL.
 *
 * @param val  A valid StatorValue pointer, or NULL.
 */
const char *stator_value_type(const StatorValue *val);

/**
 * Return the numeric value stored in `val`, or NaN if `val` is NULL or not
 * a number.
 *
 * @param val  A valid StatorValue pointer, or NULL.
 */
double stator_value_as_number(const StatorValue *val);

/**
 * Return a null-terminated C string for the string stored in `val`.
 *
 * Returns a pointer to an empty string when `val` is NULL or not a string.
 * The pointer is valid only as long as `val` is alive.
 *
 * @param val  A valid StatorValue pointer, or NULL.
 */
const char *stator_value_as_string(const StatorValue *val);

/* -------------------------------------------------------------------------
 * Object lifecycle
 * ------------------------------------------------------------------------- */

/**
 * Create a new, empty JavaScript object.
 *
 * @param isolate  A valid, non-NULL isolate pointer.
 * @return         A new StatorObject*, or NULL on failure.
 */
StatorObject *stator_object_new(StatorIsolate *isolate);

/**
 * Destroy an object and decrement the isolate's live-object counter.
 *
 * @param obj  A non-NULL pointer returned by stator_object_new().
 */
void stator_object_destroy(StatorObject *obj);

/**
 * Set (or overwrite) the named property `key` on `obj` to `val`.
 *
 * The value is copied into the object; the caller retains ownership of `val`.
 *
 * @param obj  A valid, non-NULL StatorObject pointer.
 * @param key  A null-terminated property name string.
 * @param val  A valid, non-NULL StatorValue pointer.
 */
void stator_object_set(StatorObject *obj, const char *key, const StatorValue *val);

/**
 * Get the named property `key` from `obj` as a new StatorValue.
 *
 * Returns NULL if `obj` or `key` is NULL or the property does not exist.
 * The caller owns the returned pointer and must pass it to
 * stator_value_destroy().
 *
 * @param obj  A valid, non-NULL StatorObject pointer.
 * @param key  A null-terminated property name string.
 */
StatorValue *stator_object_get(const StatorObject *obj, const char *key);

/* -------------------------------------------------------------------------
 * Script compilation (Phase 2: JavaScript parsing + bytecode generation)
 * ------------------------------------------------------------------------- */

/**
 * Compile `source` (a UTF-8 string of `source_len` bytes) to bytecode.
 *
 * The source string need not be null-terminated; exactly `source_len` bytes
 * are read.
 *
 * Always returns a non-NULL StatorScript* (even on parse errors).  The caller
 * must check stator_script_get_error() and must eventually pass the pointer to
 * stator_script_free().
 *
 * @param ctx         Execution context (may be NULL for standalone compilation).
 * @param source      Pointer to the first byte of the JavaScript source.
 * @param source_len  Length of the source string in bytes.
 * @return            A new StatorScript*, or NULL on an internal allocation
 *                    failure (extremely rare).
 */
StatorScript *stator_script_compile(StatorContext *ctx,
                                    const char    *source,
                                    size_t         source_len);

/**
 * Return a null-terminated error message if `script` compiled with an error.
 *
 * Returns NULL when `script` compiled successfully.  The returned pointer is
 * valid as long as `script` is alive (until stator_script_free() is called).
 *
 * @param script  A non-NULL pointer returned by stator_script_compile().
 */
const char *stator_script_get_error(const StatorScript *script);

/**
 * Print the decoded bytecode listing for `script` to standard output.
 *
 * Each instruction is printed on a new line in the form:
 *   "  OpcodeName [operand, ...]"
 *
 * Does nothing if `script` is NULL or compiled with an error.
 *
 * @param script  A valid StatorScript pointer, or NULL.
 */
void stator_bytecode_dump(const StatorScript *script);

/**
 * Return the number of bytecode instructions in a successfully compiled script.
 *
 * Returns 0 if `script` is NULL, compiled with an error, or the bytecode
 * stream cannot be decoded.
 *
 * @param script  A valid StatorScript pointer, or NULL.
 */
size_t stator_script_bytecode_count(const StatorScript *script);

/**
 * Free a StatorScript previously returned by stator_script_compile().
 *
 * @param script  A non-NULL pointer returned by stator_script_compile().
 *                Must not be used again after this call.
 */
void stator_script_free(StatorScript *script);

/* -------------------------------------------------------------------------
 * Handle scope lifecycle
 * ------------------------------------------------------------------------- */

/**
 * Open a new handle scope on isolate.
 *
 * All StatorValue handles created (via stator_value_new_number() or
 * stator_value_new_string()) after this call, and before the matching
 * stator_handle_scope_close(), are owned by the returned scope and will be
 * freed automatically when the scope is closed.
 *
 * The embedder must NOT call stator_value_destroy() on scope-owned handles.
 *
 * Handle scopes nest: it is valid to open multiple scopes and they must be
 * closed in LIFO order.
 *
 * Returns NULL if isolate is NULL.  The caller must eventually pass the
 * returned pointer to stator_handle_scope_close().
 *
 * @param isolate  A valid, non-NULL isolate pointer.
 * @return         A new StatorHandleScope*, or NULL if isolate is NULL.
 */
StatorHandleScope *stator_handle_scope_new(StatorIsolate *isolate);

/**
 * Close a handle scope and destroy all values registered with it.
 *
 * After this call, all StatorValue pointers created while scope was active
 * are invalid.  The previous scope (if any) is restored as the active scope.
 *
 * Does nothing if scope is NULL.
 *
 * @param scope  A non-NULL pointer returned by stator_handle_scope_new().
 *               Must be the innermost open scope.  Must not be used after
 *               this call.
 */
void stator_handle_scope_close(StatorHandleScope *scope);

/**
 * Open a new escapable handle scope on isolate.
 *
 * Like stator_handle_scope_new(), but allows a single value to be promoted
 * into the enclosing scope via stator_escapable_handle_scope_escape().
 *
 * Returns NULL if isolate is NULL.  The caller must eventually pass the
 * returned pointer to stator_escapable_handle_scope_close().
 *
 * @param isolate  A valid, non-NULL isolate pointer.
 * @return         A new StatorEscapableHandleScope*, or NULL if isolate is
 *                 NULL.
 */
StatorEscapableHandleScope *stator_escapable_handle_scope_new(StatorIsolate *isolate);

/**
 * Escape val from scope, promoting it into the enclosing scope.
 *
 * Removes val from scope's tracked handles so it will not be destroyed when
 * the scope is closed.  If there is an enclosing scope, val is registered
 * there; otherwise the caller takes ownership and must eventually pass val to
 * stator_value_destroy().
 *
 * Returns val unchanged (for convenient chaining), or NULL if scope or val
 * is NULL.
 *
 * Each value may only be escaped once.
 *
 * @param scope  A valid StatorEscapableHandleScope pointer, or NULL.
 * @param val    A non-NULL StatorValue pointer registered with scope.
 * @return       val, or NULL if scope or val is NULL.
 */
StatorValue *stator_escapable_handle_scope_escape(StatorEscapableHandleScope *scope,
                                                  StatorValue               *val);

/**
 * Close an escapable handle scope and destroy all non-escaped values.
 *
 * Equivalent to stator_handle_scope_close() for the escapable variant.
 *
 * Does nothing if scope is NULL.
 *
 * @param scope  A non-NULL pointer returned by
 *               stator_escapable_handle_scope_new().  Must be the innermost
 *               open scope.  Must not be used after this call.
 */
void stator_escapable_handle_scope_close(StatorEscapableHandleScope *scope);

/* -------------------------------------------------------------------------
 * Platform (embedder-provided task scheduling and timing)
 * ------------------------------------------------------------------------- */

/**
 * Create a new platform handle from an embedder-supplied vtable.
 *
 * The vtable is copied by value; the caller does not need to keep the
 * StatorPlatformVTable alive after this call returns.
 *
 * Returns NULL if `vtable` is NULL.  The caller must eventually pass the
 * returned pointer to stator_platform_destroy().
 *
 * @param vtable  A valid, non-NULL pointer to a StatorPlatformVTable.
 * @return        A new StatorPlatform*, or NULL if `vtable` is NULL.
 */
StatorPlatform *stator_platform_new(const StatorPlatformVTable *vtable);

/**
 * Destroy a platform previously created with stator_platform_new().
 *
 * @param platform  A non-NULL pointer returned by stator_platform_new().
 *                  Must not be used again after this call.
 */
void stator_platform_destroy(StatorPlatform *platform);

/**
 * Return the number of worker threads reported by `platform`.
 *
 * Returns 0 when `platform` is NULL or the vtable entry was not set.
 *
 * @param platform  A valid StatorPlatform pointer, or NULL.
 */
uint32_t stator_platform_number_of_worker_threads(const StatorPlatform *platform);

/**
 * Schedule `task` for execution on `platform`.
 *
 * Does nothing when `platform` is NULL, `task` is NULL, or the vtable entry
 * was not set.
 *
 * @param platform  A valid StatorPlatform pointer, or NULL.
 * @param task      An opaque task pointer; ownership transfers to the platform.
 */
void stator_platform_post_task(const StatorPlatform *platform, void *task);

/**
 * Return the monotonically increasing time (seconds) from `platform`.
 *
 * Returns 0.0 when `platform` is NULL or the vtable entry was not set.
 *
 * @param platform  A valid StatorPlatform pointer, or NULL.
 */
double stator_platform_monotonically_increasing_time(const StatorPlatform *platform);

/**
 * Return the current clock time in milliseconds from `platform`.
 *
 * Returns 0.0 when `platform` is NULL or the vtable entry was not set.
 *
 * @param platform  A valid StatorPlatform pointer, or NULL.
 */
double stator_platform_current_clock_time_millis(const StatorPlatform *platform);

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif /* STATOR_H */

